package(default_visibility = ["//visibility:public"])

exports_files([
    "ArtifactTools.csproj",
    "BUILD.bazel",
])

filegroup(
    name = "sources",
    srcs = glob(["*.cs"]) + [
        "ArtifactTools.csproj",
        "//:.editorconfig",
        "//tools:Directory.Build.props",
        "//tools:MSBuildTool.props",
    ],
)
