<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GeneratorPrefix>fixture-v1</GeneratorPrefix>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Shared/Shared.csproj" />
    <ProjectReference Include="../ClassicGenerator/ClassicGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../IncrementalGenerator/IncrementalGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../OrderOnly/OrderOnly.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="values/*.txt" />
    <CompilerVisibleProperty Include="GeneratorPrefix" />
  </ItemGroup>
</Project>
