"""Factor reviewed project mappings into defaults and prove unchanged generated bytes.

This qualification helper only shares identical existing values; it never approves
new custom documents or discovers task inputs.
"""
import argparse
import copy
import hashlib
import json
import os
from pathlib import Path
import subprocess


def compact(mapping):
    assert 'projectDefaults' not in mapping
    result = copy.deepcopy(mapping)
    projects = result['projects']
    if len(projects) < 2:
        return result
    bindings = list(projects.values())
    defaults = {}
    for key, value in list(bindings[0].items()):
        if value not in [None, [], {}] and all(row.get(key) == value for row in bindings):
            defaults[key] = copy.deepcopy(value)
            for row in bindings:
                del row[key]
    # Contracts are complete records: never factor individual hash/task fields.
    if all('documents' in row for row in bindings):
        shared = {key: copy.deepcopy(value) for key, value in bindings[0]['documents'].items() if all(row['documents'].get(key) == value for row in bindings)}
        if shared:
            defaults['documents'] = shared
            for row in bindings:
                for key in shared:
                    del row['documents'][key]
    if defaults:
        result['projectDefaults'] = defaults
    return result


def main():
    p = argparse.ArgumentParser(description=__doc__)
    for name in ['workspace', 'base', 'output']:
        p.add_argument(name, type=Path)
    a = p.parse_args()
    w, base, out = [value.resolve() for value in [a.workspace, a.base, a.output]]
    out.mkdir(parents=True, exist_ok=False)
    mapping = w / 'sync.json'; generated = w / 'projects.generated.bzl'
    original = mapping.read_bytes(); declarations = generated.read_bytes()
    (out / 'plain.json').write_bytes(original)
    reduced = (json.dumps(compact(json.loads(original)), indent=2) + '\n').encode()
    startup = [os.environ['RULES_MSBUILD_BAZEL'], '--output_base=' + str(base), '--ignore_all_rc_files']
    rows = []
    try:
        mapping.write_bytes(reduced)
        for name, args in [('check', ['--check']), ('repeat', [])]:
            result = subprocess.run(startup + ['run', '//:sync', '--jobs=2', '--', *args], cwd=w, capture_output=True, text=True)
            (out / (name + '.log')).write_text(result.stdout + result.stderr)
            assert result.returncode == 0, (name, result.stderr[-2500:])
            assert generated.read_bytes() == declarations, 'Defaults changed generated declarations'
            rows.append(dict(case=name, exitCode=result.returncode))
            print(name, 'unchanged', flush=True)
        (out / 'results.json').write_text(json.dumps(dict(projects=len(json.loads(original)['projects']), beforeBytes=len(original), afterBytes=len(reduced), reductionPercent=round(100 * (1 - len(reduced) / len(original)), 1), generatedSha256=hashlib.sha256(declarations).hexdigest(), generatedBytesUnchanged=True, controls=rows), indent=2) + '\n')
    except BaseException:
        mapping.write_bytes(original)
        raise
    finally:
        subprocess.run(startup + ['shutdown'], cwd=w, check=True)


if __name__ == '__main__':
    main()
