# Generated by ProjectSync. Edit project inputs, then synchronize again.
load("@rules_msbuild//msbuild:defs.bzl", "msbuild_graph", "msbuild_graph_runner")

def app_graph(name = "app", linux_stable_paths = False, target = "Build", linux_worker = False, worker_cache_mb = 4096, evaluation_cache_mb = 512, profile_build = False):
    if native.package_name():
        fail("app_graph must be called from the workspace root")
    msbuild_graph_runner(name = name + "_runner")
    msbuild_graph(
        name = name,
        linux_stable_paths = linux_stable_paths,
        linux_worker = linux_worker,
        worker_cache_mb = worker_cache_mb,
        evaluation_cache_mb = evaluation_cache_mb,
        profile_build = profile_build,
        target = target,
        runner = ":" + name + "_runner",
        contract = "graph.generated.json",
        srcs = ["Data/CatalogStore.cs","Data/Data.csproj","Data/products.json","Directory.Build.props","Domain/Domain.csproj","Domain/Product.cs","Services/CatalogService.cs","Services/Services.csproj","Tests/Program.cs","Tests/Tests.csproj","Web/Pages/Index.cshtml","Web/Program.cs","Web/Web.csproj","Web/wwwroot/site.css","global.json"],
        bindings = [],
        input_paths = {},
        project_outputs = {"Data/Data.csproj|net10.0":["Data/bin/Release/net10.0","Data.dll","Library"],"Domain/Domain.csproj|net10.0":["Domain/bin/Release/net10.0","Domain.dll","Library"],"Services/Services.csproj|net10.0":["Services/bin/Release/net10.0","Services.dll","Library"],"Tests/Tests.csproj|net10.0":["Tests/bin/Release/net10.0","Tests.dll","Exe"],"Web/Web.csproj|net10.0":["Web/bin/Release/net10.0","Web.dll","Exe"]},
        publish_outputs = {"Data/Data.csproj|net10.0":["Data/bin/Release/net10.0/publish","Data.dll","Library"],"Domain/Domain.csproj|net10.0":["Domain/bin/Release/net10.0/publish","Domain.dll","Library"],"Services/Services.csproj|net10.0":["Services/bin/Release/net10.0/publish","Services.dll","Library"],"Tests/Tests.csproj|net10.0":["Tests/bin/Release/net10.0/publish","Tests.dll","Exe"],"Web/Web.csproj|net10.0":["Web/bin/Release/net10.0/publish","Web.dll","Exe"]},
        package_lock = "@@//:packages",
    )
