package(default_visibility = ["//visibility:public"])

exports_files([
    "ProjectSync.csproj",
    "BUILD.bazel",
])

filegroup(
    name = "sources",
    srcs = glob(["*.cs"]) + [
        "ProjectSync.csproj",
        "//:.editorconfig",
        "//tools:Directory.Build.props",
        "//tools:GraphCompilerReferences.cs",
        "//tools:GraphEntryProperties.cs",
        "//tools:MSBuildTool.props",
        "//tools:PackageSdks.cs",
    ],
)
