using System.Text;
using System.Text.Json;
using Microsoft.Build.Evaluation;

namespace RulesMSBuild.ProjectSync;

internal sealed class Generator(string root, string sdk)
{
    private const string Header = "# Generated by ProjectSync. Edit project inputs, then synchronize again.\n";
    private readonly SortedDictionary<string, string> declarations = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> names = new(StringComparer.Ordinal);
    private readonly HashSet<string> visiting = new(StringComparer.Ordinal);

    internal static void Run(string root, string sdk, string[] projects, bool check)
    {
        if (projects.Length == 0 || !Directory.Exists(root))
        {
            throw new ArgumentException("A workspace and at least one project are required");
        }
        var generator = new Generator(root, sdk);
        foreach (var project in projects)
        {
            generator.Visit(Path.GetFullPath(project, root));
        }
        var text = Header + "load(\"@rules_msbuild//msbuild:defs.bzl\", \"msbuild_binary\", \"msbuild_project\")\n\n" + string.Join("\n", generator.declarations.Values);
        var output = Path.Combine(root, "BUILD.bazel");
        if (check)
        {
            if (!File.Exists(output) || File.ReadAllText(output) != text)
            {
                throw new InvalidDataException("BUILD.bazel is stale; rerun ProjectSync without --check");
            }
            return;
        }
        if (File.Exists(Path.Combine(root, "BUILD")) || (File.Exists(output) && !File.ReadAllText(output).StartsWith(Header, StringComparison.Ordinal)))
        {
            throw new InvalidDataException("Refusing to overwrite an authored BUILD.bazel");
        }
        var temporary = output + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllText(temporary, text);
            File.Move(temporary, output, true);
        }
        finally
        {
            File.Delete(temporary);
        }
        Console.WriteLine(output);
    }

    private string Relative(string path)
    {
        var relative = Path.GetRelativePath(root, Path.GetFullPath(path)).Replace('\\', '/');
        if (relative == ".." || relative.StartsWith("../", StringComparison.Ordinal) || Path.IsPathRooted(relative))
        {
            throw new InvalidDataException("Input outside workspace: " + path);
        }
        // This first slice emits one root Bazel package; nested packages need label mapping.
        var parent = Path.GetDirectoryName(Path.GetFullPath(path));
        while (parent is not null && parent != root)
        {
            if (File.Exists(Path.Combine(parent, "BUILD")) || File.Exists(Path.Combine(parent, "BUILD.bazel")))
            {
                throw new InvalidDataException("Nested Bazel package needs explicit label mapping: " + parent);
            }
            parent = Path.GetDirectoryName(parent);
        }
        return relative;
    }

    private static string Quote(string value) => JsonSerializer.Serialize(value);
    private static string List(IEnumerable<string> values) => "[" + string.Join(", ", values.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).Select(Quote)) + "]";
    private bool IsSdk(string path) => Path.GetFullPath(path).StartsWith(sdk + Path.DirectorySeparatorChar, StringComparison.Ordinal);

    private string Visit(string path)
    {
        var relative = Relative(path);
        var name = Path.ChangeExtension(relative, null).Replace('/', '_');
        if (names.TryGetValue(name, out var previous) && previous != path)
        {
            throw new InvalidDataException("Target name collision: " + name);
        }
        names[name] = path;
        if (declarations.ContainsKey(relative))
        {
            return name;
        }
        if (!visiting.Add(path))
        {
            throw new InvalidDataException("Project reference cycle: " + relative);
        }
        using var collection = new ProjectCollection();
        var globals = new Dictionary<string, string> { ["Configuration"] = "Release", ["Platform"] = "AnyCPU", ["ImportProjectExtensionProps"] = "false", ["ImportProjectExtensionTargets"] = "false" };
        var outer = new Project(path, globals, null, collection);
        var frameworks = outer.GetPropertyValue("TargetFrameworks");
        if (frameworks.Length == 0)
        {
            frameworks = outer.GetPropertyValue("TargetFramework");
        }
        var tfms = frameworks.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        if (tfms.Length == 0)
        {
            throw new InvalidDataException("No evaluated target frameworks: " + relative);
        }
        var variants = new List<(string Framework, string Kind, string Attributes)>();
        foreach (var tfm in tfms)
        {
            globals["TargetFramework"] = tfm;
            var project = new Project(path, globals, null, collection);
            Validate(project);
            var imports = project.Imports.Select(i => i.ImportedProject.FullPath).Where(p => !IsSdk(p)).Select(Relative).ToArray();
            var sources = project.GetItems("Compile").Select(i => Relative(i.GetMetadataValue("FullPath"))).ToArray();
            foreach (var source in sources)
            {
                if (!File.Exists(Path.Combine(root, source)))
                {
                    throw new InvalidDataException("Missing source requires a generator binding: " + source);
                }
            }
            var dependencies = project.GetItems("ProjectReference").Select(i => ":" + Visit(i.GetMetadataValue("FullPath"))).ToArray();
            var attributes = new StringBuilder();
            attributes.AppendLine("            \"srcs\": " + List(sources) + ",");
            attributes.AppendLine("            \"deps\": " + List(dependencies) + ",");
            attributes.AppendLine("            \"msbuild_imports\": " + List(imports) + ",");
            var nullable = project.GetPropertyValue("Nullable");
            attributes.AppendLine("            \"nullable\": " + Quote(nullable.Length == 0 ? "disable" : nullable) + ",");
            attributes.AppendLine("            \"lang_version\": " + Quote(project.GetPropertyValue("LangVersion")) + ",");
            attributes.AppendLine("            \"allow_unsafe\": " + (project.GetPropertyValue("AllowUnsafeBlocks").Equals("true", StringComparison.OrdinalIgnoreCase) ? "True" : "False") + ",");
            attributes.AppendLine("            \"use_apphost\": " + (project.GetPropertyValue("UseAppHost").Equals("true", StringComparison.OrdinalIgnoreCase) ? "True" : "False") + ",");
            variants.Add((tfm, project.GetPropertyValue("OutputType"), attributes.ToString()));
        }
        var binary = variants.Any(v => v.Kind != "Library");
        if (binary && (variants.Count != 1 || variants[0].Kind != "Exe"))
        {
            throw new InvalidDataException("Only single-framework console applications are supported: " + relative);
        }
        var declaration = new StringBuilder();
        declaration.AppendLine(binary ? "msbuild_binary(" : "msbuild_project(");
        declaration.AppendLine("    name = " + Quote(name) + ",");
        declaration.AppendLine("    project = " + Quote(relative) + ",");
        declaration.AppendLine("    configuration = \"Release\",");
        declaration.AppendLine("    msbuild_properties = {\"Platform\": \"AnyCPU\"},");
        if (binary)
        {
            declaration.AppendLine("    target_framework = " + Quote(tfms[0]) + ",");
            foreach (var line in variants[0].Attributes.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            {
                var colon = line.IndexOf(':');
                declaration.AppendLine("    " + JsonSerializer.Deserialize<string>(line[..colon].Trim()) + " =" + line[(colon + 1)..]);
            }
        }
        else
        {
            declaration.AppendLine("    target_frameworks = " + List(tfms) + ",");
            declaration.AppendLine("    framework_overrides = {");
            foreach (var variant in variants)
            {
                declaration.AppendLine("        " + Quote(variant.Framework) + ": {");
                declaration.Append(variant.Attributes);
                declaration.AppendLine("        },");
            }
            declaration.AppendLine("    },");
        }
        declaration.AppendLine(")");
        declarations[relative] = declaration.ToString();
        visiting.Remove(path);
        return name;
    }

    private void Validate(Project project)
    {
        var documents = project.Imports.Select(i => i.ImportedProject).Append(project.Xml).Where(p => !IsSdk(p.FullPath));
        if (project.Xml.Sdk != "Microsoft.NET.Sdk")
        {
            throw new InvalidDataException("Only Microsoft.NET.Sdk is supported: " + project.FullPath);
        }
        foreach (var item in project.AllEvaluatedItems.Where(i => !IsSdk(i.Xml.ContainingProject.FullPath)))
        {
            if (item.ItemType is not "Compile" and not "None" and not "ProjectReference" and not "PackageReference" and not "Content" and not "EmbeddedResource" and not "Reference" and not "FrameworkReference" and not "Analyzer" and not "AdditionalFiles")
            {
                throw new InvalidDataException("Item requires explicit mapping: " + item.ItemType);
            }
            if (item.ItemType == "Compile" && item.DirectMetadata.Any())
            {
                throw new InvalidDataException("Compile metadata requires explicit mapping: " + item.EvaluatedInclude);
            }
        }
        foreach (var document in documents)
        {
            _ = Relative(document.FullPath);
            if (document.Targets.Count != 0 || document.UsingTasks.Count != 0)
            {
                throw new InvalidDataException("Custom targets/tasks require explicit bindings: " + document.FullPath);
            }
        }
        if (project.GetPropertyValue("IsTestProject").Equals("true", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("Test project requires an explicit test protocol: " + project.FullPath);
        }
        foreach (var type in new[] { "PackageReference", "Reference", "FrameworkReference", "Analyzer", "AdditionalFiles", "EmbeddedResource", "Content" })
        {
            if (project.GetItems(type).Any(item => !(type == "FrameworkReference" && item.EvaluatedInclude == "Microsoft.NETCore.App" && item.GetMetadataValue("IsImplicitlyDefined") == "true") && !(type == "Analyzer" && IsSdk(item.GetMetadataValue("FullPath")))))
            {
                throw new InvalidDataException(type + " requires explicit bindings: " + project.FullPath);
            }
        }
        foreach (var item in project.GetItems("None"))
        {
            if (item.GetMetadataValue("CopyToOutputDirectory") is not "" and not "Never")
            {
                throw new InvalidDataException("Copied None item requires explicit data: " + item.EvaluatedInclude);
            }
        }
        foreach (var reference in project.GetItems("ProjectReference"))
        {
            foreach (var metadata in reference.DirectMetadata)
            {
                throw new InvalidDataException("ProjectReference metadata requires explicit mapping: " + metadata.Name);
            }
        }
    }
}
