using System.Text;
using System.Text.Json;
using Microsoft.Build.Evaluation;

namespace RulesMSBuild.ProjectSync;

internal sealed class Generator(string root, string sdk, Mappings mappings, WorkspaceView view)
{
    private const string Header = "# Generated by ProjectSync. Edit project inputs, then synchronize again.\n";
    private readonly SortedDictionary<string, string> declarations = new(StringComparer.Ordinal);
    private readonly SortedDictionary<string, string> itemDeclarations = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> names = new(StringComparer.Ordinal);
    private readonly SortedDictionary<string, string> contracts = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> activeFrameworks = new(StringComparer.Ordinal);
    private readonly HashSet<string> visiting = new(StringComparer.Ordinal);

    internal static void Run(string root, string sdk, string[] projects, bool check, Mappings mappings, WorkspaceView view, string outputRoot)
    {
        if (projects.Length == 0 || !Directory.Exists(root))
        {
            throw new ArgumentException("A workspace and at least one project are required");
        }
        var generator = new Generator(root, sdk, mappings, view);
        foreach (var project in projects)
        {
            generator.Visit(Path.GetFullPath(project, root));
        }
        foreach (var project in mappings.Tests.Keys.Concat(mappings.Projects.Keys))
        {
            if (!generator.declarations.ContainsKey(project))
            {
                throw new InvalidDataException("Project/test mapping does not match a reachable project: " + project);
            }
        }
        var body = string.Join("\n", generator.itemDeclarations.Values.Concat(generator.declarations.Values));
        var text = Header + string.Join("", generator.contracts.Select(p => "# Contract " + p.Key + " " + p.Value + "\n")) + "load(\"@rules_msbuild//msbuild:defs.bzl\", \"msbuild_binary\", \"msbuild_items\", \"msbuild_project\", \"msbuild_test_project\")\n\n" + "def app_projects():\n    if native.package_name():\n        fail(\"app_projects must be called from the workspace root\")\n" + string.Join("\n", body.TrimEnd().Split('\n').Select(line => line.Length == 0 ? "" : "    " + line)) + "\n";
        var output = Path.Combine(outputRoot, "projects.generated.bzl");
        if (check)
        {
            if (!File.Exists(output) || File.ReadAllText(output) != text)
            {
                throw new InvalidDataException("projects.generated.bzl is stale; rerun ProjectSync without --check");
            }
            return;
        }
        if (File.Exists(output) && !File.ReadAllText(output).StartsWith(Header, StringComparison.Ordinal))
        {
            throw new InvalidDataException("Refusing to overwrite an authored projects.generated.bzl");
        }
        var temporary = output + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllText(temporary, text);
            File.Move(temporary, output, true);
        }
        finally
        {
            File.Delete(temporary);
        }
        Console.WriteLine(output);
    }

    private string Relative(string path)
    {
        var relative = Path.GetRelativePath(root, Path.GetFullPath(path)).Replace('\\', '/');
        if (relative == ".." || relative.StartsWith("../", StringComparison.Ordinal) || Path.IsPathRooted(relative))
        {
            throw new InvalidDataException("Input outside workspace: " + path);
        }
        // This first slice emits one root Bazel package; nested packages need label mapping.
        var parent = Path.GetDirectoryName(Path.GetFullPath(path));
        while (parent is not null && parent != root)
        {
            if (File.Exists(Path.Combine(parent, "BUILD")) || File.Exists(Path.Combine(parent, "BUILD.bazel")))
            {
                throw new InvalidDataException("Nested Bazel package needs explicit label mapping: " + parent);
            }
            parent = Path.GetDirectoryName(parent);
        }
        return relative;
    }

    private static string Quote(string value) => StarlarkLiteral.Serialize(value);
    private static string List(IEnumerable<string> values) => "[" + string.Join(", ", values.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).Select(Quote)) + "]";
    private bool IsSdk(string path) => Path.GetFullPath(path).StartsWith(sdk + Path.DirectorySeparatorChar, StringComparison.Ordinal);

    private string Visit(string path)
    {
        var relative = Relative(path);
        var previousLock = view.PackageLock;
        try
        {
            view.SelectPackageLock(mappings.ForProject(relative).PackageLock ?? view.DefaultPackageLock);
            return VisitProject(path);
        }
        catch (Exception error) when (error is InvalidDataException or ArgumentException or Microsoft.Build.Exceptions.InvalidProjectFileException)
        {
            throw new InvalidDataException("Project " + relative + " [Configuration=Release, Platform=" + mappings.ForProject(relative).Platform + ", TargetFramework=" + activeFrameworks.GetValueOrDefault(path, "evaluation") + "]: " + error.Message, error);
        }
        finally
        {
            view.SelectPackageLock(previousLock);
        }
    }

    private string VisitProject(string path)
    {
        var relative = Relative(path);
        var name = Path.ChangeExtension(relative, null).Replace('/', '_');
        if (names.TryGetValue(name, out var previous) && previous != path)
        {
            throw new InvalidDataException("Target name collision: " + name);
        }
        names[name] = path;
        if (declarations.ContainsKey(relative))
        {
            return name;
        }
        if (!visiting.Add(path))
        {
            throw new InvalidDataException("Project reference cycle: " + relative);
        }
        mappings.Tests.TryGetValue(relative, out var test);
        using var collection = new ProjectCollection();
        var projectBinding = mappings.ForProject(relative);
        var properties = mappings.ProjectProperties(relative, test);
        var globals = new Dictionary<string, string>(properties, StringComparer.OrdinalIgnoreCase) { ["Configuration"] = "Release", ["ImportProjectExtensionProps"] = "false", ["ImportProjectExtensionTargets"] = "false" };
        foreach (var (nameOfProperty, value) in view.ToolProperties(projectBinding.Bindings))
        {
            globals.Add(nameOfProperty, value);
        }
        if (test is not null)
        {
            if (test.OutputType is not null)
            {
                globals["OutputType"] = test.OutputType == "exe" ? "Exe" : "Library";
            }
        }
        if (projectBinding.UseAppHost is { } useAppHost)
        {
            globals["UseAppHost"] = useAppHost.ToString();
        }
        var outer = new Project(path, globals, null, collection);
        var frameworks = outer.GetPropertyValue("TargetFrameworks");
        if (frameworks.Length == 0)
        {
            frameworks = outer.GetPropertyValue("TargetFramework");
        }
        var tfms = frameworks.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        if (tfms.Length == 0)
        {
            throw new InvalidDataException("No evaluated target frameworks: " + relative);
        }
        if (projectBinding.TargetFrameworks.Length != 0)
        {
            if (projectBinding.TargetFrameworks.Except(tfms, StringComparer.Ordinal).Any())
            {
                throw new InvalidDataException("Selected target framework is not declared by project: " + relative);
            }
            tfms = projectBinding.TargetFrameworks.Order(StringComparer.Ordinal).ToArray();
        }
        if (projectBinding.FrameworkOverrides.Keys.Except(tfms, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("Framework override does not match selected frameworks: " + relative);
        }
        var baseBinding = projectBinding;
        var variants = new List<(string Framework, string Kind, string Attributes)>();
        var activeDocuments = new HashSet<string>(StringComparer.Ordinal);
        var usedItemPaths = new HashSet<string>(StringComparer.Ordinal);
        foreach (var tfm in tfms)
        {
            activeFrameworks[path] = tfm;
            projectBinding = baseBinding.FrameworkOverrides.GetValueOrDefault(tfm) ?? baseBinding;
            view.SelectPackageLock(projectBinding.PackageLock ?? view.DefaultPackageLock);
            var variantProperties = mappings.ProjectProperties(relative, test, projectBinding);
            var variantGlobals = new Dictionary<string, string>(variantProperties, StringComparer.OrdinalIgnoreCase)
            {
                ["Configuration"] = "Release",
                ["ImportProjectExtensionProps"] = "false",
                ["ImportProjectExtensionTargets"] = "false",
                ["TargetFramework"] = tfm
            };
            foreach (var (property, value) in view.ToolProperties(projectBinding.Bindings))
            {
                variantGlobals.Add(property, value);
            }
            if (test?.OutputType is not null)
            {
                variantGlobals["OutputType"] = test.OutputType == "exe" ? "Exe" : "Library";
            }
            if (projectBinding.UseAppHost is { } variantUseAppHost)
            {
                variantGlobals["UseAppHost"] = variantUseAppHost.ToString();
            }
            var project = new Project(path, variantGlobals, null, collection);
            Validate(project, test, projectBinding);
            activeDocuments.UnionWith(project.Imports.Select(i => i.ImportedProject.FullPath).Append(project.FullPath).Where(p => !IsSdk(p)).Select(p => Path.GetRelativePath(root, p).Replace('\\', '/')));
            var packages = mappings.PackageAttributes(project, projectBinding);
            var privacy = Mappings.PackagePrivacy(project, projectBinding);
            var imports = project.Imports.Select(i => i.ImportedProject.FullPath).Where(p => !IsSdk(p) && !view.IsPackage(p)).Select(Relative).ToArray();
            if (view.PackageLock is not null && File.Exists(Path.Combine(root, "global.json")))
            {
                imports = imports.Append("global.json").ToArray();
            }
            imports = imports.Concat(projectBinding.Documents.Values.SelectMany(d => d.Inputs).Select(path => Relative(Path.Combine(root, WorkspaceView.Safe(path))))).ToArray();
            foreach (var input in imports)
            {
                if (!File.Exists(Path.Combine(root, input)))
                {
                    throw new InvalidDataException("Missing contract input: " + input);
                }
            }
            var sources = project.GetItems("Compile").Select(i => Relative(i.GetMetadataValue("FullPath"))).ToArray();
            foreach (var source in sources)
            {
                if (!File.Exists(Path.Combine(root, source)))
                {
                    throw new InvalidDataException("Missing source requires a generator binding: " + source);
                }
            }
            var roles = References(project, projectBinding);
            var dependencies = roles["deps"].Concat(packages["deps"]).ToArray();
            var attributes = new StringBuilder();
            if (!variantProperties.OrderBy(p => p.Key, StringComparer.Ordinal).SequenceEqual(properties.OrderBy(p => p.Key, StringComparer.Ordinal)))
            {
                attributes.AppendLine("            \"msbuild_properties\": " + StarlarkLiteral.Serialize(variantProperties) + ",");
            }
            attributes.AppendLine("            \"package_private_assets\": " + StarlarkLiteral.Serialize(privacy) + ",");
            attributes.AppendLine("            \"package_reference_paths\": " + StarlarkLiteral.Serialize(projectBinding.PackageReferencePaths) + ",");
            attributes.AppendLine("            \"transitive_compile_references\": " + (projectBinding.TransitiveCompileReferences ? "True" : "False") + ",");
            if (projectBinding.LinuxWorker)
            {
                attributes.AppendLine("            \"linux_worker\": True,");
            }
            if (projectBinding.ProfileBuild)
            {
                attributes.AppendLine("            \"profile_build\": True,");
            }
            var frameworkReferences = project.GetItems("FrameworkReference").Where(i => (i.EvaluatedInclude is not "Microsoft.NETCore.App" and not "NETStandard.Library") || !i.GetMetadataValue("IsImplicitlyDefined").Equals("true", StringComparison.OrdinalIgnoreCase)).Select(i => i.EvaluatedInclude).ToArray();
            if (frameworkReferences.Length != 0)
            {
                attributes.AppendLine("            \"framework_refs\": " + List(frameworkReferences) + ",");
            }
            if (projectBinding.ExportTargets.Count != 0)
            {
                attributes.AppendLine("            \"export_targets\": " + StarlarkLiteral.Serialize(projectBinding.ExportTargets) + ",");
            }
            // Analyzer behavior on partial types can depend on evaluated source order.
            attributes.AppendLine("            \"srcs\": " + StarlarkLiteral.Serialize(sources.Where(p => !view.Labels.ContainsKey(p)).Distinct(StringComparer.Ordinal)) + ",");
            attributes.AppendLine("            \"source_paths\": " + StarlarkLiteral.Serialize(view.Bindings(sources)) + ",");
            attributes.AppendLine("            \"deps\": " + List(dependencies) + ",");
            attributes.AppendLine("            \"items\": " + StarlarkLiteral.Serialize(InputItems(project, relative, tfm, projectBinding, usedItemPaths).Concat(projectBinding.Items).Concat(roles["items"]).Distinct(StringComparer.Ordinal).ToArray()) + ",");
            attributes.AppendLine("            \"msbuild_imports\": " + List(imports.Where(p => !view.Labels.ContainsKey(p))) + ",");
            attributes.AppendLine("            \"import_paths\": " + StarlarkLiteral.Serialize(view.Bindings(imports)) + ",");
            if (view.PackageLock is not null)
            {
                attributes.AppendLine("            \"package_lock\": " + Quote(view.PackageLock) + ",");
            }
            foreach (var role in new[] { "build_deps", "analyzers" })
            {
                attributes.AppendLine("            " + Quote(role) + ": " + List(packages[role].Concat(roles.GetValueOrDefault(role) ?? [])) + ",");
            }
            foreach (var role in new[] { "implementation_deps", "tools", "project_outputs", "reference_packages", "framework_assemblies" })
            {
                attributes.AppendLine("            " + Quote(role) + ": " + List(roles[role].Concat(role == "tools" ? projectBinding.Tools : [])) + ",");
            }
            attributes.AppendLine("            \"reference_projects\": " + StarlarkLiteral.Serialize(projectBinding.References.Where(p => p.Value.Role == "compile").ToDictionary(p => p.Value.Label, p => p.Key)) + ",");
            attributes.AppendLine("            \"assembly_selections\": " + List(projectBinding.AssemblySelections) + ",");
            attributes.AppendLine("            \"bindings\": " + List(projectBinding.Bindings) + ",");
            attributes.AppendLine("            \"adapter_imports\": " + List(projectBinding.AdapterImports) + ",");
            attributes.AppendLine("            \"layout_bindings\": " + StarlarkLiteral.Serialize(projectBinding.LayoutBindings) + ",");
            attributes.AppendLine("            \"directories\": " + List(projectBinding.Directories) + ",");
            if (projectBinding.GeneratedDirectories.Count != 0)
            {
                attributes.AppendLine("            \"generated_directories\": " + StarlarkLiteral.Serialize(projectBinding.GeneratedDirectories) + ",");
            }
            attributes.AppendLine("            \"output_mode\": " + Quote(projectBinding.OutputMode) + ",");
            if (projectBinding.ReferencePack is not null)
            {
                attributes.AppendLine("            \"reference_pack\": " + Quote(projectBinding.ReferencePack) + ",");
            }
            if (projectBinding.RuntimeHost is not null)
            {
                attributes.AppendLine("            \"runtime_host\": " + Quote(projectBinding.RuntimeHost) + ",");
            }
            if (test is not null)
            {
                foreach (var (key, value) in Mappings.TestAttributes(test, project.GetPropertyValue("OutputType")))
                {
                    attributes.AppendLine("            " + Quote(key) + ": " + StarlarkLiteral.Serialize(value) + ",");
                }
            }
            attributes.AppendLine("            \"assembly_name\": " + Quote(project.GetPropertyValue("AssemblyName")) + ",");
            var nullable = project.GetPropertyValue("Nullable");
            attributes.AppendLine("            \"nullable\": " + Quote(nullable.Length == 0 ? "disable" : nullable) + ",");
            attributes.AppendLine("            \"lang_version\": " + Quote(project.GetPropertyValue("LangVersion")) + ",");
            attributes.AppendLine("            \"allow_unsafe\": " + (project.GetPropertyValue("AllowUnsafeBlocks").Equals("true", StringComparison.OrdinalIgnoreCase) ? "True" : "False") + ",");
            attributes.AppendLine("            \"use_apphost\": " + (project.GetPropertyValue("UseAppHost").Equals("true", StringComparison.OrdinalIgnoreCase) ? "True" : "False") + ",");
            variants.Add((tfm, project.GetPropertyValue("OutputType"), attributes.ToString()));
        }
        if (baseBinding.FrameworkOverrides.Values.Prepend(baseBinding).SelectMany(b => b.ItemPaths.Keys).Except(usedItemPaths, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("Item path mapping does not match evaluated file items: " + relative);
        }
        if (baseBinding.FrameworkOverrides.Values.Prepend(baseBinding).SelectMany(b => b.Documents.Keys).Except(activeDocuments, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("Custom document mapping does not match evaluated imports: " + relative);
        }
        var binary = test is null && variants.Any(v => v.Kind != "Library");
        if (binary && (variants.Count != 1 || variants[0].Kind != "Exe"))
        {
            throw new InvalidDataException("Only single-framework console applications are supported: " + relative);
        }
        var declaration = new StringBuilder();
        declaration.AppendLine(test is not null ? "msbuild_test_project(" : binary ? "msbuild_binary(" : "msbuild_project(");
        declaration.AppendLine("    name = " + Quote(name) + ",");
        declaration.AppendLine("    project = " + Quote(relative) + ",");
        declaration.AppendLine("    configuration = \"Release\",");
        declaration.AppendLine("    msbuild_properties = " + StarlarkLiteral.Serialize(binary ? mappings.ProjectProperties(relative, test, projectBinding) : properties) + ",");
        if (binary)
        {
            declaration.AppendLine("    target_framework = " + Quote(tfms[0]) + ",");
            foreach (var line in variants[0].Attributes.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            {
                var colon = line.IndexOf(':');
                var attribute = JsonSerializer.Deserialize<string>(line[..colon].Trim());
                if (attribute != "msbuild_properties")
                {
                    declaration.AppendLine("    " + attribute + " =" + line[(colon + 1)..]);
                }
            }
        }
        else
        {
            declaration.AppendLine("    target_frameworks = " + List(tfms) + ",");
            declaration.AppendLine("    framework_overrides = {");
            foreach (var variant in variants)
            {
                declaration.AppendLine("        " + Quote(variant.Framework) + ": {");
                declaration.Append(variant.Attributes);
                declaration.AppendLine("        },");
            }
            declaration.AppendLine("    },");
        }
        declaration.AppendLine(")");
        declarations[relative] = declaration.ToString();
        visiting.Remove(path);
        activeFrameworks.Remove(path);
        return name;
    }

    private Dictionary<string, List<string>> References(Project project, ProjectBinding binding)
    {
        var roles = new[] { "deps", "implementation_deps", "analyzers", "tools", "project_outputs", "reference_packages", "framework_assemblies", "build_deps", "items" }.ToDictionary(role => role, _ => new List<string>(), StringComparer.Ordinal);
        var observed = new HashSet<string>(StringComparer.Ordinal);
        foreach (var item in project.GetItems("ProjectReference"))
        {
            var path = Relative(item.GetMetadataValue("FullPath"));
            observed.Add(path);
            if (binding.ProjectReferences.TryGetValue(path, out var bound))
            {
                var attribute = bound.Role switch
                {
                    "compile" => "deps",
                    "private" => "implementation_deps",
                    "analyzer" => "analyzers",
                    "tool" => "tools",
                    "output" => "project_outputs",
                    "items" => "items",
                    _ => throw new InvalidDataException("Invalid ProjectReference role: " + bound.Role)
                };
                var output = item.GetMetadataValue("OutputItemType");
                var reference = item.GetMetadataValue("ReferenceOutputAssembly");
                if (bound.Role == "analyzer" && (output != "Analyzer" || !reference.Equals("false", StringComparison.OrdinalIgnoreCase)) || bound.Role == "tool" && (output.Length != 0 || !reference.Equals("false", StringComparison.OrdinalIgnoreCase)) || bound.Role is "compile" or "private" && (output.Length != 0 || reference.Length != 0 && !reference.Equals("true", StringComparison.OrdinalIgnoreCase)))
                {
                    throw new InvalidDataException("ProjectReference role disagrees with mapping: " + path);
                }
                if (bound.Role == "items")
                {
                    if (output != bound.OutputItemType || item.GetMetadataValue("Targets") != bound.Targets || !reference.Equals("false", StringComparison.OrdinalIgnoreCase))
                    {
                        throw new InvalidDataException("ProjectReference item output disagrees with mapping: " + path);
                    }
                    roles[attribute].AddRange(bound.Labels);
                }
                else
                {
                    roles[attribute].Add(bound.Label);
                }
            }
            else
            {
                if (item.Metadata.Any(m => !IsSdk(m.Xml.ContainingProject.FullPath)))
                {
                    throw new InvalidDataException("ProjectReference metadata requires explicit mapping: " + path + "; declare projectReferences[\"" + path + "\"] with its intended role");
                }
                roles["deps"].Add(":" + Visit(item.GetMetadataValue("FullPath")));
            }
        }
        if (binding.ProjectReferences.Keys.Except(observed, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("ProjectReference mapping does not match evaluated items: " + project.FullPath);
        }
        observed.Clear();
        foreach (var item in project.GetItems("Reference"))
        {
            if (Path.IsPathRooted(item.EvaluatedInclude) && view.IsPackage(Path.GetFullPath(item.EvaluatedInclude)))
            {
                var identity = Relative(item.EvaluatedInclude);
                var parts = identity.Split('/');
                var assetPath = string.Join('/', parts.Skip(4));
                if (view.PackageLock is null || parts.Length < 5 || !binding.PackageReferencePaths.TryGetValue(parts[2], out var assets) || !assets.Contains(assetPath, StringComparer.Ordinal) || !File.Exists(item.EvaluatedInclude))
                {
                    throw new InvalidDataException("Package file Reference requires an existing locked package reference path: " + identity);
                }
                if (item.Metadata.Any(m => m.Name is "HintPath" or "Aliases" or "SpecificVersion" or "EmbedInteropTypes"))
                {
                    throw new InvalidDataException("Unsupported package file Reference metadata: " + identity);
                }
                continue;
            }
            observed.Add(item.EvaluatedInclude);
            if (!binding.References.TryGetValue(item.EvaluatedInclude, out var bound))
            {
                throw new InvalidDataException("Reference requires explicit mapping: " + item.EvaluatedInclude);
            }
            if (item.Metadata.Any(m => m.Name is "HintPath" or "Aliases" or "SpecificVersion" or "EmbedInteropTypes"))
            {
                throw new InvalidDataException("Unsupported mapped Reference metadata: " + item.EvaluatedInclude);
            }
            if (bound.Role == "compile")
            {
                continue;
            }
            var role = bound.Role switch
            {
                "package" => "reference_packages",
                "framework" => "framework_assemblies",
                _ => throw new InvalidDataException("Bare references require package/framework bindings: " + item.EvaluatedInclude)
            };
            roles[role].Add(bound.Role == "framework" ? item.EvaluatedInclude : bound.Label);
            foreach (var assetRole in bound.Roles)
            {
                roles[assetRole].Add(bound.Label);
            }
        }
        if (binding.References.Keys.Except(observed, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("Reference mapping does not match evaluated items: " + project.FullPath);
        }
        return roles;
    }

    private IEnumerable<string> InputItems(Project project, string relative, string framework, ProjectBinding binding, HashSet<string> usedItemPaths)
    {
        var signingKey = project.GetPropertyValue("AssemblyOriginatorKeyFile");
        if (signingKey.Length != 0)
        {
            var keyPath = Relative(Path.GetFullPath(signingKey, Path.GetDirectoryName(project.FullPath)!));
            if (!File.Exists(Path.Combine(root, keyPath)))
            {
                throw new InvalidDataException("Missing signing key input: " + keyPath);
            }
            if (!view.IsPackage(Path.Combine(root, keyPath)))
            {
                var keyName = "_sync_key_" + Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(Encoding.UTF8.GetBytes(keyPath)));
                itemDeclarations[keyName] = "msbuild_items(\n    name = " + Quote(keyName) + ",\n    item_type = \"None\",\n    srcs = " + List(view.Labels.ContainsKey(keyPath) ? [] : [keyPath]) + ",\n    paths = " + StarlarkLiteral.Serialize(view.Bindings([keyPath])) + ",\n)\n";
                yield return ":" + keyName;
            }
        }
        foreach (var type in new[] { "Compile", "EmbeddedResource", "AdditionalFiles", "EditorConfigFiles", "GlobalAnalyzerConfigFiles", "Content", "None" }.Concat(binding.InputItems.Keys).Distinct(StringComparer.Ordinal))
        {
            foreach (var item in project.GetItems(type))
            {
                // SDK config discovery includes absent ancestor candidates. Only
                // existing files are compiler inputs; authored missing files fail.
                if (type is "EditorConfigFiles" or "GlobalAnalyzerConfigFiles" && IsSdk(item.Xml.ContainingProject.FullPath) && (!File.Exists(item.GetMetadataValue("FullPath")) || IsSdk(item.GetMetadataValue("FullPath"))))
                {
                    continue;
                }
                if (type == "Compile" && !item.Metadata.Any(m => m.Name is "Link" or "LinkBase" or "SubType") || type == "None" && !binding.InputItems.ContainsKey(type) && item.GetMetadataValue("CopyToOutputDirectory") is "" or "Never" && item.GetMetadataValue("CopyToPublishDirectory") is "" or "Never")
                {
                    continue;
                }
                var allowed = type == "Compile" ? new[] { "Link", "LinkBase", "SubType", "Visible", "DesignTime", "AutoGen", "DependentUpon", "CopyToOutputDirectory", "CopyToPublishDirectory", "TargetPath" } : new[] { "Link", "LinkBase", "LogicalName", "ManifestResourceName", "Culture", "WithCulture", "CopyToOutputDirectory", "CopyToPublishDirectory", "TargetPath", "Visible", "Pack", "PackagePath", "CopyToBuildDirectory", "GenerateSource", "ClassName", "Generator", "Language", "SubType", "Namespace", "GenerateResourcesCodeAsConstants", "StronglyTypedClassName", "StronglyTypedNamespace", "DependentUpon", "LastGenOutput" };
                foreach (var metadata in item.Metadata.Where(m => !IsSdk(m.Xml.ContainingProject.FullPath)))
                {
                    if (!allowed.Contains(metadata.Name, StringComparer.Ordinal) && !(binding.InputItems.GetValueOrDefault(type) ?? []).Contains(metadata.Name, StringComparer.Ordinal) || metadata.Name == "GenerateSource" && binding.Documents.Count == 0)
                    {
                        throw new InvalidDataException(type + " metadata requires explicit binding: " + metadata.Name);
                    }
                }
                var metadataValues = new SortedDictionary<string, string>(StringComparer.Ordinal);
                foreach (var key in allowed.Concat(binding.InputItems.GetValueOrDefault(type) ?? []).Distinct(StringComparer.Ordinal))
                {
                    var value = item.GetMetadataValue(key);
                    if (value.Length == 0)
                    {
                        continue;
                    }
                    if (Path.IsPathRooted(value) || value.Contains("$(", StringComparison.Ordinal) || value.Contains("@(", StringComparison.Ordinal))
                    {
                        throw new InvalidDataException("Unsafe item metadata: " + key);
                    }
                    metadataValues.Add(key, value);
                }
                var path = Relative(item.GetMetadataValue("FullPath"));
                if (!File.Exists(Path.Combine(root, path)))
                {
                    throw new InvalidDataException("Missing input requires a generator binding: " + path);
                }
                var paths = view.Bindings([path]);
                if (binding.ItemPaths.TryGetValue(path, out var destination))
                {
                    usedItemPaths.Add(path);
                    if (type == "Compile")
                    {
                        throw new InvalidDataException("Compile path remapping requires a source binding");
                    }

                    paths[view.Labels.GetValueOrDefault(path, ":" + path)] = destination;
                }
                var identity = JsonSerializer.Serialize(new
                {
                    relative,
                    framework,
                    type,
                    path,
                    paths,
                    metadataValues
                });
                var name = "_sync_item_" + Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(Encoding.UTF8.GetBytes(identity)));
                if (names.TryGetValue(name, out var previous) && previous != identity)
                {
                    throw new InvalidDataException("Target name collision: " + name);
                }
                names[name] = identity;
                itemDeclarations[name] = "msbuild_items(\n    name = " + Quote(name) + ",\n    item_type = " + Quote(type) + ",\n    srcs = " + List(paths.Count != 0 ? [] : [path]) + ",\n    paths = " + StarlarkLiteral.Serialize(paths) + ",\n    metadata = " + StarlarkLiteral.Serialize(metadataValues) + ",\n)\n";
                yield return ":" + name;
            }
        }
    }

    private void Validate(Project project, TestBinding? test, ProjectBinding binding)
    {
        var documents = project.Imports.Select(i => i.ImportedProject).Append(project.Xml).Where(p => !IsSdk(p.FullPath)).DistinctBy(p => p.FullPath).ToArray();
        if (project.Xml.Sdk is not "Microsoft.NET.Sdk" and not "Microsoft.NET.Sdk.Web" and not "Microsoft.NET.Sdk.Razor")
        {
            throw new InvalidDataException("Only Microsoft.NET.Sdk, Microsoft.NET.Sdk.Web and Microsoft.NET.Sdk.Razor are supported: " + project.FullPath);
        }
        foreach (var item in project.AllEvaluatedItems.Where(i => !IsSdk(i.Xml.ContainingProject.FullPath)))
        {
            if (!binding.EvaluationItems.Contains(item.ItemType, StringComparer.Ordinal) && !binding.InputItems.ContainsKey(item.ItemType) && item.ItemType is not "InternalsVisibleTo" and not "Compile" and not "None" and not "ProjectReference" and not "PackageReference" and not "PackageVersion" and not "Content" and not "EmbeddedResource" and not "Reference" and not "FrameworkReference" and not "Analyzer" and not "AdditionalFiles" and not "EditorConfigFiles" and not "GlobalAnalyzerConfigFiles" and not "Using")
            {
                throw new InvalidDataException("Item requires explicit mapping: " + item.ItemType + " Include=\"" + item.EvaluatedInclude + "\" from " + Relative(item.Xml.ContainingProject.FullPath) + "; declare evaluationItems for reviewed bookkeeping or an explicit input binding");
            }
        }
        foreach (var item in project.GetItems("Compile"))
        {
            if (item.Metadata.Any(m => !IsSdk(m.Xml.ContainingProject.FullPath) && m.Name is not "Link" and not "LinkBase" and not "SubType" and not "Visible" and not "DesignTime" and not "AutoGen" and not "DependentUpon" and not "CopyToOutputDirectory" and not "CopyToPublishDirectory" and not "TargetPath"))
            {
                throw new InvalidDataException("Compile metadata requires explicit mapping: " + item.EvaluatedInclude);
            }
        }
        foreach (var document in documents)
        {
            var logical = view.IsPackage(document.FullPath) ? Path.GetRelativePath(root, document.FullPath).Replace('\\', '/') : Relative(document.FullPath);
            if (!binding.Documents.TryGetValue(logical, out var contract))
            {
                if (document.Targets.Count == 0 && document.UsingTasks.Count == 0)
                {
                    continue;
                }
                throw new InvalidDataException("Custom targets/tasks require explicit bindings: " + logical + "; declare documents[\"" + logical + "\"] with reviewed sha256, targets, tasks and inputs");
            }
            var digest = Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(document.FullPath)));
            if (contract.Sha256 != digest || !document.Targets.Select(t => t.Name).ToHashSet(StringComparer.Ordinal).SetEquals(contract.Targets) || !document.UsingTasks.Select(t => t.TaskName).ToHashSet(StringComparer.Ordinal).SetEquals(contract.Tasks))
            {
                throw new InvalidDataException("Custom document contract changed: " + logical);
            }
            if (contract.Tasks.Length != 0 && binding.Tools.Length == 0 && binding.ProjectReferences.Values.All(r => r.Role != "tool") && view.PackageLock is null)
            {
                throw new InvalidDataException("Custom tasks require declared tools or package_lock: " + logical);
            }
            contracts[logical] = digest;
        }
        foreach (var item in project.GetItems("Using"))
        {
            if (item.Metadata.Any(m => m.Name is not "Alias" and not "Static"))
            {
                throw new InvalidDataException("Unsupported Using metadata: " + item.EvaluatedInclude);
            }
        }
        foreach (var friend in project.GetItems("InternalsVisibleTo"))
        {
            if (friend.Metadata.Any(m => m.Name is not "Key" and not "AllInternalsVisible" and not "Visible"))
            {
                throw new InvalidDataException("Unsupported InternalsVisibleTo metadata: " + friend.EvaluatedInclude);
            }
        }
        if (test is null && project.GetPropertyValue("IsTestProject").Equals("true", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("Test project requires an explicit test protocol: " + project.FullPath);
        }
        foreach (var framework in project.GetItems("FrameworkReference"))
        {
            if (framework.Metadata.Any(m => !IsSdk(m.Xml.ContainingProject.FullPath) && m.Name != "IsImplicitlyDefined"))
            {
                throw new InvalidDataException("FrameworkReference metadata requires explicit support: " + framework.EvaluatedInclude);
            }
        }
        if (project.GetItems("Analyzer").Any(item => !IsSdk(item.GetMetadataValue("FullPath"))))
        {
            throw new InvalidDataException("Analyzer requires explicit bindings: " + project.FullPath);
        }
        foreach (var target in binding.ExportTargets.Keys)
        {
            if (!project.Targets.ContainsKey(target))
            {
                throw new InvalidDataException("Export target is not declared in the evaluated project: " + target);
            }
        }
    }
}
