using System.Text;
using System.Text.Json;
using Microsoft.Build.Evaluation;

namespace RulesMSBuild.ProjectSync;

internal sealed class Generator(string root, string sdk, Mappings mappings, WorkspaceView view)
{
    private const string Header = "# Generated by ProjectSync. Edit project inputs, then synchronize again.\n";
    private readonly SortedDictionary<string, string> declarations = new(StringComparer.Ordinal);
    private readonly SortedDictionary<string, string> itemDeclarations = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> names = new(StringComparer.Ordinal);
    private readonly SortedDictionary<string, string> contracts = new(StringComparer.Ordinal);
    private readonly HashSet<string> visiting = new(StringComparer.Ordinal);

    internal static void Run(string root, string sdk, string[] projects, bool check, Mappings mappings, WorkspaceView view, string outputRoot)
    {
        if (projects.Length == 0 || !Directory.Exists(root))
        {
            throw new ArgumentException("A workspace and at least one project are required");
        }
        var generator = new Generator(root, sdk, mappings, view);
        foreach (var project in projects)
        {
            generator.Visit(Path.GetFullPath(project, root));
        }
        foreach (var project in mappings.Tests.Keys.Concat(mappings.Projects.Keys))
        {
            if (!generator.declarations.ContainsKey(project))
            {
                throw new InvalidDataException("Project/test mapping does not match a reachable project: " + project);
            }
        }
        var body = string.Join("\n", generator.itemDeclarations.Values.Concat(generator.declarations.Values));
        var text = Header + string.Join("", generator.contracts.Select(p => "# Contract " + p.Key + " " + p.Value + "\n")) + "load(\"@rules_msbuild//msbuild:defs.bzl\", \"msbuild_binary\", \"msbuild_items\", \"msbuild_project\", \"msbuild_test_project\")\n\n" + "def app_projects():\n    if native.package_name():\n        fail(\"app_projects must be called from the workspace root\")\n" + string.Join("\n", body.TrimEnd().Split('\n').Select(line => line.Length == 0 ? "" : "    " + line)) + "\n";
        var output = Path.Combine(outputRoot, "projects.generated.bzl");
        if (check)
        {
            if (!File.Exists(output) || File.ReadAllText(output) != text)
            {
                throw new InvalidDataException("projects.generated.bzl is stale; rerun ProjectSync without --check");
            }
            return;
        }
        if (File.Exists(output) && !File.ReadAllText(output).StartsWith(Header, StringComparison.Ordinal))
        {
            throw new InvalidDataException("Refusing to overwrite an authored projects.generated.bzl");
        }
        var temporary = output + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            File.WriteAllText(temporary, text);
            File.Move(temporary, output, true);
        }
        finally
        {
            File.Delete(temporary);
        }
        Console.WriteLine(output);
    }

    private string Relative(string path)
    {
        var relative = Path.GetRelativePath(root, Path.GetFullPath(path)).Replace('\\', '/');
        if (relative == ".." || relative.StartsWith("../", StringComparison.Ordinal) || Path.IsPathRooted(relative))
        {
            throw new InvalidDataException("Input outside workspace: " + path);
        }
        // This first slice emits one root Bazel package; nested packages need label mapping.
        var parent = Path.GetDirectoryName(Path.GetFullPath(path));
        while (parent is not null && parent != root)
        {
            if (File.Exists(Path.Combine(parent, "BUILD")) || File.Exists(Path.Combine(parent, "BUILD.bazel")))
            {
                throw new InvalidDataException("Nested Bazel package needs explicit label mapping: " + parent);
            }
            parent = Path.GetDirectoryName(parent);
        }
        return relative;
    }

    private static string Quote(string value) => JsonSerializer.Serialize(value);
    private static string List(IEnumerable<string> values) => "[" + string.Join(", ", values.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).Select(Quote)) + "]";
    private bool IsSdk(string path) => Path.GetFullPath(path).StartsWith(sdk + Path.DirectorySeparatorChar, StringComparison.Ordinal);

    private string Visit(string path)
    {
        var relative = Relative(path);
        var name = Path.ChangeExtension(relative, null).Replace('/', '_');
        if (names.TryGetValue(name, out var previous) && previous != path)
        {
            throw new InvalidDataException("Target name collision: " + name);
        }
        names[name] = path;
        if (declarations.ContainsKey(relative))
        {
            return name;
        }
        if (!visiting.Add(path))
        {
            throw new InvalidDataException("Project reference cycle: " + relative);
        }
        mappings.Tests.TryGetValue(relative, out var test);
        using var collection = new ProjectCollection();
        var projectBinding = mappings.Projects.GetValueOrDefault(relative) ?? new ProjectBinding();
        var properties = mappings.ProjectProperties(relative, test);
        var globals = new Dictionary<string, string>(properties, StringComparer.OrdinalIgnoreCase) { ["Configuration"] = "Release", ["ImportProjectExtensionProps"] = "false", ["ImportProjectExtensionTargets"] = "false" };
        foreach (var (nameOfProperty, value) in view.ToolProperties(projectBinding.Bindings))
        {
            globals.Add(nameOfProperty, value);
        }
        if (test is not null)
        {
            if (test.OutputType is not null)
            {
                globals["OutputType"] = test.OutputType == "exe" ? "Exe" : "Library";
            }
        }
        var outer = new Project(path, globals, null, collection);
        var frameworks = outer.GetPropertyValue("TargetFrameworks");
        if (frameworks.Length == 0)
        {
            frameworks = outer.GetPropertyValue("TargetFramework");
        }
        var tfms = frameworks.Split(';', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal).ToArray();
        if (tfms.Length == 0)
        {
            throw new InvalidDataException("No evaluated target frameworks: " + relative);
        }
        if (mappings.Projects.TryGetValue(relative, out var binding) && binding.TargetFrameworks.Length != 0)
        {
            if (binding.TargetFrameworks.Except(tfms, StringComparer.Ordinal).Any())
            {
                throw new InvalidDataException("Selected target framework is not declared by project: " + relative);
            }
            tfms = binding.TargetFrameworks.Order(StringComparer.Ordinal).ToArray();
        }
        var variants = new List<(string Framework, string Kind, string Attributes)>();
        var activeDocuments = new HashSet<string>(StringComparer.Ordinal);
        foreach (var tfm in tfms)
        {
            globals["TargetFramework"] = tfm;
            var project = new Project(path, globals, null, collection);
            Validate(project, test, projectBinding);
            activeDocuments.UnionWith(project.Imports.Select(i => i.ImportedProject.FullPath).Append(project.FullPath).Where(p => !IsSdk(p)).Select(p => Path.GetRelativePath(root, p).Replace('\\', '/')));
            var packages = mappings.PackageAttributes(project);
            var privacy = Mappings.PackagePrivacy(project);
            var imports = project.Imports.Select(i => i.ImportedProject.FullPath).Where(p => !IsSdk(p) && !view.IsPackage(p)).Select(Relative).ToArray();
            if (view.PackageLock is not null && File.Exists(Path.Combine(root, "global.json")))
            {
                imports = imports.Append("global.json").ToArray();
            }
            imports = imports.Concat(projectBinding.Documents.Values.SelectMany(d => d.Inputs).Select(path => Relative(Path.Combine(root, WorkspaceView.Safe(path))))).ToArray();
            foreach (var input in imports)
            {
                if (!File.Exists(Path.Combine(root, input)))
                {
                    throw new InvalidDataException("Missing contract input: " + input);
                }
            }
            var sources = project.GetItems("Compile").Select(i => Relative(i.GetMetadataValue("FullPath"))).ToArray();
            foreach (var source in sources)
            {
                if (!File.Exists(Path.Combine(root, source)))
                {
                    throw new InvalidDataException("Missing source requires a generator binding: " + source);
                }
            }
            var roles = References(project, projectBinding);
            var dependencies = roles["deps"].Concat(packages["deps"]).ToArray();
            var attributes = new StringBuilder();
            attributes.AppendLine("            \"package_private_assets\": " + JsonSerializer.Serialize(privacy) + ",");
            attributes.AppendLine("            \"srcs\": " + List(sources.Where(p => !view.Labels.ContainsKey(p))) + ",");
            attributes.AppendLine("            \"source_paths\": " + JsonSerializer.Serialize(view.Bindings(sources)) + ",");
            attributes.AppendLine("            \"deps\": " + List(dependencies) + ",");
            attributes.AppendLine("            \"items\": " + List(InputItems(project, relative, tfm).Concat(projectBinding.Items)) + ",");
            attributes.AppendLine("            \"msbuild_imports\": " + List(imports.Where(p => !view.Labels.ContainsKey(p))) + ",");
            attributes.AppendLine("            \"import_paths\": " + JsonSerializer.Serialize(view.Bindings(imports)) + ",");
            if (view.PackageLock is not null)
            {
                attributes.AppendLine("            \"package_lock\": " + Quote(view.PackageLock) + ",");
            }
            foreach (var role in new[] { "build_deps", "analyzers" })
            {
                attributes.AppendLine("            " + Quote(role) + ": " + List(packages[role].Concat(roles.GetValueOrDefault(role) ?? [])) + ",");
            }
            foreach (var role in new[] { "implementation_deps", "tools", "project_outputs", "reference_packages", "framework_assemblies" })
            {
                attributes.AppendLine("            " + Quote(role) + ": " + List(roles[role].Concat(role == "tools" ? projectBinding.Tools : [])) + ",");
            }
            attributes.AppendLine("            \"reference_projects\": " + JsonSerializer.Serialize(projectBinding.References.Where(p => p.Value.Role == "compile").ToDictionary(p => p.Value.Label, p => p.Key)) + ",");
            attributes.AppendLine("            \"bindings\": " + List(projectBinding.Bindings) + ",");
            attributes.AppendLine("            \"adapter_imports\": " + List(projectBinding.AdapterImports) + ",");
            attributes.AppendLine("            \"layout_bindings\": " + JsonSerializer.Serialize(projectBinding.LayoutBindings) + ",");
            attributes.AppendLine("            \"directories\": " + List(projectBinding.Directories) + ",");
            attributes.AppendLine("            \"output_mode\": " + Quote(projectBinding.OutputMode) + ",");
            if (projectBinding.ReferencePack is not null)
            {
                attributes.AppendLine("            \"reference_pack\": " + Quote(projectBinding.ReferencePack) + ",");
            }
            if (projectBinding.RuntimeHost is not null)
            {
                attributes.AppendLine("            \"runtime_host\": " + Quote(projectBinding.RuntimeHost) + ",");
            }
            if (test is not null)
            {
                foreach (var (key, value) in Mappings.TestAttributes(test, project.GetPropertyValue("OutputType")))
                {
                    attributes.AppendLine("            " + Quote(key) + ": " + JsonSerializer.Serialize(value) + ",");
                }
            }
            attributes.AppendLine("            \"assembly_name\": " + Quote(project.GetPropertyValue("AssemblyName")) + ",");
            var nullable = project.GetPropertyValue("Nullable");
            attributes.AppendLine("            \"nullable\": " + Quote(nullable.Length == 0 ? "disable" : nullable) + ",");
            attributes.AppendLine("            \"lang_version\": " + Quote(project.GetPropertyValue("LangVersion")) + ",");
            attributes.AppendLine("            \"allow_unsafe\": " + (project.GetPropertyValue("AllowUnsafeBlocks").Equals("true", StringComparison.OrdinalIgnoreCase) ? "True" : "False") + ",");
            attributes.AppendLine("            \"use_apphost\": " + (project.GetPropertyValue("UseAppHost").Equals("true", StringComparison.OrdinalIgnoreCase) ? "True" : "False") + ",");
            variants.Add((tfm, project.GetPropertyValue("OutputType"), attributes.ToString()));
        }
        if (projectBinding.Documents.Keys.Except(activeDocuments, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("Custom document mapping does not match evaluated imports: " + relative);
        }
        var binary = test is null && variants.Any(v => v.Kind != "Library");
        if (binary && (variants.Count != 1 || variants[0].Kind != "Exe"))
        {
            throw new InvalidDataException("Only single-framework console applications are supported: " + relative);
        }
        var declaration = new StringBuilder();
        declaration.AppendLine(test is not null ? "msbuild_test_project(" : binary ? "msbuild_binary(" : "msbuild_project(");
        declaration.AppendLine("    name = " + Quote(name) + ",");
        declaration.AppendLine("    project = " + Quote(relative) + ",");
        declaration.AppendLine("    configuration = \"Release\",");
        declaration.AppendLine("    msbuild_properties = " + JsonSerializer.Serialize(properties) + ",");
        if (binary)
        {
            declaration.AppendLine("    target_framework = " + Quote(tfms[0]) + ",");
            foreach (var line in variants[0].Attributes.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            {
                var colon = line.IndexOf(':');
                declaration.AppendLine("    " + JsonSerializer.Deserialize<string>(line[..colon].Trim()) + " =" + line[(colon + 1)..]);
            }
        }
        else
        {
            declaration.AppendLine("    target_frameworks = " + List(tfms) + ",");
            declaration.AppendLine("    framework_overrides = {");
            foreach (var variant in variants)
            {
                declaration.AppendLine("        " + Quote(variant.Framework) + ": {");
                declaration.Append(variant.Attributes);
                declaration.AppendLine("        },");
            }
            declaration.AppendLine("    },");
        }
        declaration.AppendLine(")");
        declarations[relative] = declaration.ToString();
        visiting.Remove(path);
        return name;
    }

    private Dictionary<string, List<string>> References(Project project, ProjectBinding binding)
    {
        var roles = new[] { "deps", "implementation_deps", "analyzers", "tools", "project_outputs", "reference_packages", "framework_assemblies" }.ToDictionary(role => role, _ => new List<string>(), StringComparer.Ordinal);
        var observed = new HashSet<string>(StringComparer.Ordinal);
        foreach (var item in project.GetItems("ProjectReference"))
        {
            var path = Relative(item.GetMetadataValue("FullPath"));
            observed.Add(path);
            if (binding.ProjectReferences.TryGetValue(path, out var bound))
            {
                var attribute = bound.Role switch
                {
                    "compile" => "deps",
                    "private" => "implementation_deps",
                    "analyzer" => "analyzers",
                    "tool" => "tools",
                    "output" => "project_outputs",
                    _ => throw new InvalidDataException("Invalid ProjectReference role: " + bound.Role)
                };
                var output = item.GetMetadataValue("OutputItemType");
                var reference = item.GetMetadataValue("ReferenceOutputAssembly");
                if (bound.Role == "analyzer" && (output != "Analyzer" || !reference.Equals("false", StringComparison.OrdinalIgnoreCase)) || bound.Role == "tool" && (output.Length != 0 || !reference.Equals("false", StringComparison.OrdinalIgnoreCase)) || bound.Role is "compile" or "private" && (output.Length != 0 || reference.Length != 0 && !reference.Equals("true", StringComparison.OrdinalIgnoreCase)))
                {
                    throw new InvalidDataException("ProjectReference role disagrees with mapping: " + path);
                }
                roles[attribute].Add(bound.Label);
            }
            else
            {
                if (item.Metadata.Any(m => !IsSdk(m.Xml.ContainingProject.FullPath)))
                {
                    throw new InvalidDataException("ProjectReference metadata requires explicit mapping: " + path);
                }
                roles["deps"].Add(":" + Visit(item.GetMetadataValue("FullPath")));
            }
        }
        if (binding.ProjectReferences.Keys.Except(observed, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("ProjectReference mapping does not match evaluated items: " + project.FullPath);
        }
        observed.Clear();
        foreach (var item in project.GetItems("Reference"))
        {
            observed.Add(item.EvaluatedInclude);
            if (!binding.References.TryGetValue(item.EvaluatedInclude, out var bound))
            {
                throw new InvalidDataException("Reference requires explicit mapping: " + item.EvaluatedInclude);
            }
            if (item.Metadata.Any(m => m.Name is "HintPath" or "Aliases" or "SpecificVersion" or "EmbedInteropTypes"))
            {
                throw new InvalidDataException("Unsupported mapped Reference metadata: " + item.EvaluatedInclude);
            }
            if (bound.Role == "compile")
            {
                continue;
            }
            var role = bound.Role switch
            {
                "package" => "reference_packages",
                "framework" => "framework_assemblies",
                _ => throw new InvalidDataException("Bare references require package/framework bindings: " + item.EvaluatedInclude)
            };
            roles[role].Add(bound.Role == "framework" ? item.EvaluatedInclude : bound.Label);
        }
        if (binding.References.Keys.Except(observed, StringComparer.Ordinal).Any())
        {
            throw new InvalidDataException("Reference mapping does not match evaluated items: " + project.FullPath);
        }
        return roles;
    }

    private IEnumerable<string> InputItems(Project project, string relative, string framework)
    {
        var signingKey = project.GetPropertyValue("AssemblyOriginatorKeyFile");
        if (signingKey.Length != 0)
        {
            var keyPath = Relative(Path.GetFullPath(signingKey, Path.GetDirectoryName(project.FullPath)!));
            if (!File.Exists(Path.Combine(root, keyPath)))
            {
                throw new InvalidDataException("Missing signing key input: " + keyPath);
            }
            var keyName = "_sync_key_" + Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(Encoding.UTF8.GetBytes(keyPath)));
            itemDeclarations[keyName] = "msbuild_items(\n    name = " + Quote(keyName) + ",\n    item_type = \"None\",\n    srcs = " + List(view.Labels.ContainsKey(keyPath) ? [] : [keyPath]) + ",\n    paths = " + JsonSerializer.Serialize(view.Bindings([keyPath])) + ",\n)\n";
            yield return ":" + keyName;
        }
        foreach (var type in new[] { "Compile", "EmbeddedResource", "AdditionalFiles", "Content", "None" })
        {
            foreach (var item in project.GetItems(type))
            {
                if (type == "Compile" && !item.Metadata.Any(m => m.Name is "Link" or "LinkBase") || type == "None" && item.GetMetadataValue("CopyToOutputDirectory") is "" or "Never" && item.GetMetadataValue("CopyToPublishDirectory") is "" or "Never")
                {
                    continue;
                }
                var allowed = type == "Compile" ? new[] { "Link", "LinkBase" } : new[] { "Link", "LinkBase", "LogicalName", "ManifestResourceName", "Culture", "WithCulture", "CopyToOutputDirectory", "CopyToPublishDirectory", "TargetPath" };
                foreach (var metadata in item.Metadata.Where(m => !IsSdk(m.Xml.ContainingProject.FullPath)))
                {
                    if (!allowed.Contains(metadata.Name, StringComparer.Ordinal))
                    {
                        throw new InvalidDataException(type + " metadata requires explicit binding: " + metadata.Name);
                    }
                }
                var metadataValues = new SortedDictionary<string, string>(StringComparer.Ordinal);
                foreach (var key in allowed)
                {
                    var value = item.GetMetadataValue(key);
                    if (value.Length == 0)
                    {
                        continue;
                    }
                    if (Path.IsPathRooted(value) || value.Contains("$(", StringComparison.Ordinal) || value.Contains("@(", StringComparison.Ordinal))
                    {
                        throw new InvalidDataException("Unsafe item metadata: " + key);
                    }
                    metadataValues.Add(key, value);
                }
                var path = Relative(item.GetMetadataValue("FullPath"));
                if (!File.Exists(Path.Combine(root, path)))
                {
                    throw new InvalidDataException("Missing input requires a generator binding: " + path);
                }
                var identity = JsonSerializer.Serialize(new
                {
                    relative,
                    framework,
                    type,
                    path,
                    metadataValues
                });
                var name = "_sync_item_" + Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(Encoding.UTF8.GetBytes(identity)));
                if (names.TryGetValue(name, out var previous) && previous != identity)
                {
                    throw new InvalidDataException("Target name collision: " + name);
                }
                names[name] = identity;
                itemDeclarations[name] = "msbuild_items(\n    name = " + Quote(name) + ",\n    item_type = " + Quote(type) + ",\n    srcs = " + List(view.Labels.ContainsKey(path) ? [] : [path]) + ",\n    paths = " + JsonSerializer.Serialize(view.Bindings([path])) + ",\n    metadata = " + JsonSerializer.Serialize(metadataValues) + ",\n)\n";
                yield return ":" + name;
            }
        }
    }

    private void Validate(Project project, TestBinding? test, ProjectBinding binding)
    {
        var documents = project.Imports.Select(i => i.ImportedProject).Append(project.Xml).Where(p => !IsSdk(p.FullPath)).DistinctBy(p => p.FullPath).ToArray();
        if (project.Xml.Sdk != "Microsoft.NET.Sdk")
        {
            throw new InvalidDataException("Only Microsoft.NET.Sdk is supported: " + project.FullPath);
        }
        foreach (var item in project.AllEvaluatedItems.Where(i => !IsSdk(i.Xml.ContainingProject.FullPath)))
        {
            if (!binding.EvaluationItems.Contains(item.ItemType, StringComparer.Ordinal) && item.ItemType is not "InternalsVisibleTo" and not "Compile" and not "None" and not "ProjectReference" and not "PackageReference" and not "PackageVersion" and not "Content" and not "EmbeddedResource" and not "Reference" and not "FrameworkReference" and not "Analyzer" and not "AdditionalFiles")
            {
                throw new InvalidDataException("Item requires explicit mapping: " + item.ItemType);
            }
        }
        foreach (var item in project.GetItems("Compile"))
        {
            if (item.Metadata.Any(m => !IsSdk(m.Xml.ContainingProject.FullPath) && m.Name is not "Link" and not "LinkBase"))
            {
                throw new InvalidDataException("Compile metadata requires explicit mapping: " + item.EvaluatedInclude);
            }
        }
        foreach (var document in documents)
        {
            var logical = view.IsPackage(document.FullPath) ? Path.GetRelativePath(root, document.FullPath).Replace('\\', '/') : Relative(document.FullPath);
            if (!binding.Documents.TryGetValue(logical, out var contract))
            {
                if (document.Targets.Count == 0 && document.UsingTasks.Count == 0)
                {
                    continue;
                }
                throw new InvalidDataException("Custom targets/tasks require explicit bindings: " + logical);
            }
            var digest = Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(document.FullPath)));
            if (contract.Sha256 != digest || !document.Targets.Select(t => t.Name).ToHashSet(StringComparer.Ordinal).SetEquals(contract.Targets) || !document.UsingTasks.Select(t => t.TaskName).ToHashSet(StringComparer.Ordinal).SetEquals(contract.Tasks))
            {
                throw new InvalidDataException("Custom document contract changed: " + logical);
            }
            if (contract.Tasks.Length != 0 && binding.Tools.Length == 0 && binding.ProjectReferences.Values.All(r => r.Role != "tool") && view.PackageLock is null)
            {
                throw new InvalidDataException("Custom tasks require declared tools or package_lock: " + logical);
            }
            contracts[logical] = digest;
        }
        foreach (var friend in project.GetItems("InternalsVisibleTo"))
        {
            if (friend.Metadata.Any(m => m.Name is not "Key" and not "AllInternalsVisible"))
            {
                throw new InvalidDataException("Unsupported InternalsVisibleTo metadata: " + friend.EvaluatedInclude);
            }
        }
        if (test is null && project.GetPropertyValue("IsTestProject").Equals("true", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("Test project requires an explicit test protocol: " + project.FullPath);
        }
        foreach (var type in new[] { "FrameworkReference", "Analyzer" })
        {
            if (project.GetItems(type).Any(item => !(type == "FrameworkReference" && item.EvaluatedInclude == "Microsoft.NETCore.App" && item.GetMetadataValue("IsImplicitlyDefined") == "true") && !(type == "Analyzer" && IsSdk(item.GetMetadataValue("FullPath")))))
            {
                throw new InvalidDataException(type + " requires explicit bindings: " + project.FullPath);
            }
        }
    }
}
