using System.Text.Json;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Graph;

namespace RulesMSBuild.ProjectSync;

// The first graph-sync slice deliberately admits only package-free SDK projects.
// Richer mappings must transfer their input contracts before they can opt in.
internal static class GraphGenerator
{
    private const string Header = "# Generated by ProjectSync --graph. Edit project inputs, then synchronize again.\n";
    private const string ContractName = "graph.generated.json";
    private const string BuildName = "graph.generated.bzl";
    private static readonly string[] FileItems = ["Compile", "EmbeddedResource", "Content", "None", "AdditionalFiles", "Analyzer", "EditorConfigFiles", "GlobalAnalyzerConfigFiles"];

    internal static void Run(string root, string sdk, string[] entries, bool check, string outputRoot)
    {
        if (entries.Length != 1)
        {
            throw new InvalidDataException("Graph sync requires one project entry point");
        }
        root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(root));
        sdk = Path.TrimEndingDirectorySeparator(sdk);
        var sdkRoot = Path.GetDirectoryName(Path.GetDirectoryName(sdk))!;
        using var collection = new ProjectCollection();
        var inputs = new System.Collections.Concurrent.ConcurrentDictionary<string, string[]>();
        var properties = new Dictionary<string, string> { ["Configuration"] = "Release" };
        var evaluationProperties = new Dictionary<string, string>(properties)
        {
            ["ImportProjectExtensionProps"] = "false",
            ["ImportProjectExtensionTargets"] = "false",
            ["UseSharedCompilation"] = "false",
            ["PathMap"] = root + "=/_/workspace," + sdkRoot + "=/_/sdk"
        };
        var entry = WorkspaceView.Safe(entries[0]);
        var graph = new ProjectGraph(new[] { new ProjectGraphEntryPoint(Path.Combine(root, entry), evaluationProperties) }, collection,
            (path, globals, projects) =>
            {
                var project = new Project(path, globals, null, projects);
                if (project.Xml.Sdk != "Microsoft.NET.Sdk" || project.GetItems("PackageReference").Count != 0 ||
                    project.GetPropertyValue("IsTestProject").Equals("true", StringComparison.OrdinalIgnoreCase) ||
                    project.GetItems("Reference").Count != 0)
                {
                    throw new InvalidDataException("Graph sync currently requires package-free Microsoft.NET.Sdk projects without test or assembly-reference mappings: " + Relative(path));
                }
                var documents = project.Imports.Select(import => import.ImportedProject).Append(project.Xml)
                    .Where(document => !IsSdk(document.FullPath)).DistinctBy(document => document.FullPath).ToArray();
                if (documents.Any(document => document.Targets.Count != 0 || document.UsingTasks.Count != 0))
                {
                    throw new InvalidDataException("Graph sync custom targets/tasks still require contract transfer: " + Relative(path));
                }
                foreach (var item in project.AllEvaluatedItems.Where(item => !IsSdk(item.Xml.ContainingProject.FullPath)))
                {
                    if (!FileItems.Contains(item.ItemType, StringComparer.Ordinal) && item.ItemType is not "ProjectReference" and not "InternalsVisibleTo" and not "Using" and not "FrameworkReference")
                    {
                        throw new InvalidDataException("Graph sync item requires contract transfer: " + item.ItemType);
                    }
                }
                var declared = new HashSet<string>(documents.Select(document => Relative(document.FullPath)), StringComparer.Ordinal);
                foreach (var item in FileItems.SelectMany(project.GetItems))
                {
                    var fullPath = item.GetMetadataValue("FullPath");
                    if (fullPath.Length == 0 || IsSdk(fullPath))
                    {
                        continue;
                    }
                    if (!File.Exists(fullPath) && IsSdk(item.Xml.ContainingProject.FullPath))
                    {
                        continue;
                    }
                    var relative = Relative(fullPath);
                    if (relative is ContractName or BuildName)
                    {
                        continue;
                    }
                    if (!File.Exists(fullPath))
                    {
                        throw new InvalidDataException("Graph sync input does not exist: " + relative);
                    }
                    declared.Add(relative);
                }
                var instance = project.CreateProjectInstance();
                inputs[Key(instance)] = declared.Order(StringComparer.Ordinal).ToArray();
                return instance;
            });
        var declarations = new SortedDictionary<string, object>(StringComparer.Ordinal);
        foreach (var group in graph.ProjectNodes.GroupBy(node => Relative(node.ProjectInstance.FullPath)))
        {
            // Including the union makes an absent global property explicit. This
            // prevents an outer-node selector from also matching an inner node.
            var selectorKeys = group.SelectMany(node => node.ProjectInstance.GlobalProperties.Keys)
                .Where(key => !evaluationProperties.ContainsKey(key) || properties.ContainsKey(key))
                .Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.Ordinal).ToArray();
            var configurations = group.OrderBy(node => Key(node.ProjectInstance), StringComparer.Ordinal).Select(node => new
            {
                Properties = selectorKeys.ToDictionary(key => key, key => node.ProjectInstance.GlobalProperties.TryGetValue(key, out var value) ? value : ""),
                Inputs = inputs[Key(node.ProjectInstance)],
                OutputDirectories = node.ProjectInstance.GetPropertyValue("TargetPath").Length == 0 ? [] :
                    new[] { "OutputPath", "IntermediateOutputPath" }.Select(property =>
                    {
                        var value = node.ProjectInstance.GetPropertyValue(property);
                        if (value.Length == 0)
                        {
                            throw new InvalidDataException("Missing graph output property: " + property);
                        }
                        return Relative(Path.TrimEndingDirectorySeparator(Path.GetFullPath(value.Replace('\\', '/'), Path.GetDirectoryName(node.ProjectInstance.FullPath)!)));
                    }).Distinct().ToArray()
            }).ToArray();
            declarations.Add(group.Key, new
            {
                Inputs = Array.Empty<string>(),
                OutputDirectories = Array.Empty<string>(),
                Configurations = configurations
            });
        }
        var shared = File.Exists(Path.Combine(root, "global.json")) ? new[] { "global.json" } : [];
        var contract = JsonSerializer.Serialize(new
        {
            GeneratedBy = "ProjectSync --graph",
            Version = 2,
            Entry = entry,
            SdkVersion = Path.GetFileName(sdk),
            Properties = properties,
            SharedInputs = shared,
            Projects = declarations
        }, new JsonSerializerOptions { WriteIndented = true }) + "\n";
        var sources = inputs.Values.SelectMany(files => files).Concat(shared).Distinct().Order(StringComparer.Ordinal).ToArray();
        var text = Header + "load(\"@rules_msbuild//msbuild:defs.bzl\", \"msbuild_graph\", \"msbuild_graph_runner\")\n\n" +
            "def app_graph(name = \"app\"):\n    if native.package_name():\n        fail(\"app_graph must be called from the workspace root\")\n" +
            "    msbuild_graph_runner(name = name + \"_runner\")\n    msbuild_graph(\n        name = name,\n        runner = \":\" + name + \"_runner\",\n" +
            "        contract = \"" + ContractName + "\",\n        srcs = " + StarlarkLiteral.Serialize(sources) + ",\n    )\n";
        // Validate both destinations before replacing either generated file.
        Verify(ContractName, contract, "{\n  \"GeneratedBy\": \"ProjectSync --graph\",");
        Verify(BuildName, text, Header);
        if (!check)
        {
            File.WriteAllText(Path.Combine(outputRoot, ContractName), contract);
            File.WriteAllText(Path.Combine(outputRoot, BuildName), text);
        }

        bool IsSdk(string path) => Path.GetFullPath(path).StartsWith(sdkRoot + Path.DirectorySeparatorChar, StringComparison.Ordinal);
        string Relative(string path)
        {
            var relative = WorkspaceView.Safe(Path.GetRelativePath(root, path).Replace('\\', '/'));
            var parent = Path.GetDirectoryName(Path.GetFullPath(path));
            while (parent is not null && parent != root)
            {
                if (File.Exists(Path.Combine(parent, "BUILD")) || File.Exists(Path.Combine(parent, "BUILD.bazel")))
                {
                    throw new InvalidDataException("Graph sync requires a root Bazel package: " + relative);
                }
                parent = Path.GetDirectoryName(parent);
            }
            return relative;
        }
        void Verify(string name, string expected, string header)
        {
            var path = Path.Combine(outputRoot, name);
            if (check && (!File.Exists(path) || File.ReadAllText(path) != expected))
            {
                throw new InvalidDataException(name + " is stale; rerun ProjectSync --graph");
            }
            if (!check && File.Exists(path) && !File.ReadAllText(path).StartsWith(header, StringComparison.Ordinal))
            {
                throw new InvalidDataException("Refusing to overwrite an authored " + name);
            }
        }
    }

    private static string Key(Microsoft.Build.Execution.ProjectInstance project) => project.FullPath + "|" +
        string.Join(";", project.GlobalProperties.OrderBy(property => property.Key, StringComparer.Ordinal).Select(property => property.Key + "=" + property.Value));
}
