using System.Text.Json;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Graph;

namespace RulesMSBuild.ProjectSync;

// The first graph-sync slice deliberately admits only package-free SDK projects.
// Richer mappings must transfer their input contracts before they can opt in.
internal static class GraphGenerator
{
    private const string Header = "# Generated by ProjectSync --graph. Edit project inputs, then synchronize again.\n";
    private const string ContractName = "graph.generated.json";
    private const string BuildName = "graph.generated.bzl";
    private static readonly string[] FileItems = ["Compile", "EmbeddedResource", "Content", "None", "AdditionalFiles", "Analyzer", "EditorConfigFiles", "GlobalAnalyzerConfigFiles"];

    internal static void Run(string root, string sdk, string[] entries, bool check, string outputRoot)
    {
        root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(root));
        sdk = Path.TrimEndingDirectorySeparator(sdk);
        var sdkRoot = Path.GetDirectoryName(Path.GetDirectoryName(sdk))!;
        using var collection = new ProjectCollection();
        var inputs = new System.Collections.Concurrent.ConcurrentDictionary<string, string[]>();
        var definitions = new System.Collections.Concurrent.ConcurrentDictionary<string, byte>();
        var properties = new Dictionary<string, string> { ["Configuration"] = "Release" };
        var evaluationProperties = new Dictionary<string, string>(properties)
        {
            ["ImportProjectExtensionProps"] = "false",
            ["ImportProjectExtensionTargets"] = "false",
            ["UseSharedCompilation"] = "false",
            ["PathMap"] = root + "=/_/workspace," + sdkRoot + "=/_/sdk"
        };
        var entry = WorkspaceView.Safe(entries[0]);
        var graph = new ProjectGraph(entries.Select(path => new ProjectGraphEntryPoint(Path.Combine(root, WorkspaceView.Safe(path)), evaluationProperties)), collection,
            (path, globals, projects) =>
            {
                var project = new Project(path, globals, null, projects);
                if (project.Xml.Sdk != "Microsoft.NET.Sdk" || project.GetItems("PackageReference").Count != 0 ||
                    project.GetPropertyValue("IsTestProject").Equals("true", StringComparison.OrdinalIgnoreCase) ||
                    project.GetItems("Reference").Count != 0)
                {
                    throw new InvalidDataException("Graph sync currently requires package-free Microsoft.NET.Sdk projects without test or assembly-reference mappings: " + Relative(path));
                }
                var documents = project.Imports.Select(import => import.ImportedProject).Append(project.Xml)
                    .Where(document => !IsSdk(document.FullPath)).DistinctBy(document => document.FullPath).ToArray();
                if (documents.Any(document => document.Targets.Count != 0 || document.UsingTasks.Count != 0))
                {
                    throw new InvalidDataException("Graph sync custom targets/tasks still require contract transfer: " + Relative(path));
                }
                foreach (var item in project.AllEvaluatedItems.Where(item => !IsSdk(item.Xml.ContainingProject.FullPath)))
                {
                    if (!FileItems.Contains(item.ItemType, StringComparer.Ordinal) && item.ItemType is not "ProjectReference" and not "InternalsVisibleTo" and not "Using" and not "FrameworkReference")
                    {
                        throw new InvalidDataException("Graph sync item requires contract transfer: " + item.ItemType);
                    }
                }
                var declared = new HashSet<string>(documents.Select(document => Relative(document.FullPath)), StringComparer.Ordinal);
                foreach (var document in declared)
                {
                    definitions.TryAdd(document, 0);
                }
                foreach (var item in FileItems.SelectMany(project.GetItems))
                {
                    var fullPath = item.GetMetadataValue("FullPath");
                    if (fullPath.Length == 0 || IsSdk(fullPath))
                    {
                        continue;
                    }
                    if (!File.Exists(fullPath) && IsSdk(item.Xml.ContainingProject.FullPath))
                    {
                        continue;
                    }
                    var relative = Relative(fullPath);
                    if (relative is ContractName or BuildName)
                    {
                        continue;
                    }
                    if (!File.Exists(fullPath))
                    {
                        throw new InvalidDataException("Graph sync input does not exist: " + relative);
                    }
                    declared.Add(relative);
                }
                var instance = project.CreateProjectInstance();
                inputs[Key(instance)] = declared.Order(StringComparer.Ordinal).ToArray();
                return instance;
            });
        var dependencyClosure = new Dictionary<ProjectGraphNode, HashSet<ProjectGraphNode>>();
        var boundaries = new Dictionary<ProjectGraphNode, bool>();
        var declarations = new SortedDictionary<string, object>(StringComparer.Ordinal);
        foreach (var group in graph.ProjectNodes.GroupBy(node => Relative(node.ProjectInstance.FullPath)))
        {
            // Including the union makes an absent global property explicit. This
            // prevents an outer-node selector from also matching an inner node.
            var selectorKeys = group.SelectMany(node => node.ProjectInstance.GlobalProperties.Keys)
                .Where(key => !evaluationProperties.ContainsKey(key) || properties.ContainsKey(key))
                .Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.Ordinal).ToArray();
            var configurations = group.OrderBy(node => Key(node.ProjectInstance), StringComparer.Ordinal).Select(node => new
            {
                Properties = selectorKeys.ToDictionary(key => key, key => node.ProjectInstance.GlobalProperties.TryGetValue(key, out var value) ? value : ""),
                Inputs = inputs[Key(node.ProjectInstance)],
                ReferenceBoundary = CanUseReferenceBoundary(node),
                DependencyCopies = CanUseReferenceBoundary(node) ? DependencyCopies(node) : new Dictionary<string, string>(),
                OutputDirectories = node.ProjectInstance.GetPropertyValue("TargetPath").Length == 0 ? [] :
                    new[] { "OutputPath", "IntermediateOutputPath" }.Select(property =>
                    {
                        var value = node.ProjectInstance.GetPropertyValue(property);
                        if (value.Length == 0)
                        {
                            throw new InvalidDataException("Missing graph output property: " + property);
                        }
                        return Relative(Path.TrimEndingDirectorySeparator(Path.GetFullPath(value.Replace('\\', '/'), Path.GetDirectoryName(node.ProjectInstance.FullPath)!)));
                    }).Distinct().ToArray()
            }).ToArray();
            declarations.Add(group.Key, new
            {
                Inputs = Array.Empty<string>(),
                OutputDirectories = Array.Empty<string>(),
                Configurations = configurations
            });
        }
        var shared = File.Exists(Path.Combine(root, "global.json")) ? new[] { "global.json" } : [];
        var contract = JsonSerializer.Serialize(new
        {
            GeneratedBy = "ProjectSync --graph",
            Version = 2,
            Entry = entry,
            Entries = entries,
            SdkVersion = Path.GetFileName(sdk),
            Properties = properties,
            SharedInputs = shared,
            DefinitionDigests = definitions.Keys.Order(StringComparer.Ordinal).ToDictionary(path => path,
                path => Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(Path.Combine(root, path))))),
            Projects = declarations
        }, new JsonSerializerOptions { WriteIndented = true }) + "\n";
        var sources = inputs.Values.SelectMany(files => files).Concat(shared).Distinct().Order(StringComparer.Ordinal).ToArray();
        var runtimeOutputs = graph.ProjectNodes.Where(node => node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 &&
            node.ProjectInstance.GetPropertyValue("TargetFramework").Length != 0).OrderBy(node => Key(node.ProjectInstance), StringComparer.Ordinal).ToDictionary(
            node => Relative(node.ProjectInstance.FullPath) + "|" + node.ProjectInstance.GetPropertyValue("TargetFramework"),
            node => new[] { Relative(Path.GetDirectoryName(node.ProjectInstance.GetPropertyValue("TargetPath"))!),
                Path.GetFileName(node.ProjectInstance.GetPropertyValue("TargetPath")), node.ProjectInstance.GetPropertyValue("OutputType") });
        var text = Header + "load(\"@rules_msbuild//msbuild:defs.bzl\", \"msbuild_graph\", \"msbuild_graph_runner\")\n\n" +
            "def app_graph(name = \"app\"):\n    if native.package_name():\n        fail(\"app_graph must be called from the workspace root\")\n" +
            "    msbuild_graph_runner(name = name + \"_runner\")\n    msbuild_graph(\n        name = name,\n        runner = \":\" + name + \"_runner\",\n" +
            "        contract = \"" + ContractName + "\",\n        srcs = " + StarlarkLiteral.Serialize(sources) + ",\n        project_outputs = " + StarlarkLiteral.Serialize(runtimeOutputs) + ",\n    )\n";
        // Validate both destinations before replacing either generated file.
        Verify(ContractName, contract, "{\n  \"GeneratedBy\": \"ProjectSync --graph\",");
        Verify(BuildName, text, Header);
        if (!check)
        {
            File.WriteAllText(Path.Combine(outputRoot, ContractName), contract);
            File.WriteAllText(Path.Combine(outputRoot, BuildName), text);
        }

        IEnumerable<ProjectGraphNode> Dependencies(ProjectGraphNode node)
        {
            if (dependencyClosure.TryGetValue(node, out var existing))
            {
                return existing;
            }
            var seen = new HashSet<ProjectGraphNode>();
            var pending = new Stack<ProjectGraphNode>(node.ProjectReferences);
            while (pending.TryPop(out var dependency))
            {
                if (seen.Add(dependency))
                {
                    foreach (var child in dependency.ProjectReferences)
                    {
                        pending.Push(child);
                    }
                }
            }
            dependencyClosure.Add(node, seen);
            return seen;
        }
        bool CanUseReferenceBoundary(ProjectGraphNode node)
        {
            if (boundaries.TryGetValue(node, out var boundary))
            {
                return boundary;
            }
            return boundaries[node] = node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 &&
            Dependencies(node).Append(node).All(current =>
                new[] { "PublishTrimmed", "PublishReadyToRun", "PublishAot", "PublishSingleFile" }.All(property =>
                    !current.ProjectInstance.GetPropertyValue(property).Equals("true", StringComparison.OrdinalIgnoreCase)) &&
                current.ProjectInstance.GetItems("ProjectReference").All(item =>
                    item.GetMetadataValue("OutputItemType").Length == 0 &&
                    item.GetMetadataValue("Targets").Length == 0 &&
                    item.GetMetadataValue("ReferenceOutputAssembly") is "" or "true" &&
                    item.GetMetadataValue("Private") is "" or "true") &&
                (current == node || current.ProjectInstance.GetPropertyValue("OutputType").Equals("Library", StringComparison.OrdinalIgnoreCase)) &&
                HasStandardSymbols(current) &&
                current.ProjectInstance.GetItems("EmbeddedResource").Count == 0 &&
                FileItems.SelectMany(current.ProjectInstance.GetItems).All(item =>
                    item.GetMetadataValue("CopyToOutputDirectory") is "" or "Never" &&
                    item.GetMetadataValue("CopyToPublishDirectory") is "" or "Never"));
        }

        bool HasStandardSymbols(ProjectGraphNode node)
        {
            var project = node.ProjectInstance;
            var target = project.GetPropertyValue("TargetPath");
            if (Path.GetExtension(target) != ".dll" || project.GetPropertyValue("PdbFile").Length != 0)
            {
                return false;
            }
            var documentation = project.GetPropertyValue("DocumentationFile");
            if (documentation.Length == 0)
            {
                return true;
            }
            var directory = Path.GetDirectoryName(project.FullPath)!;
            var expected = Path.Combine(project.GetPropertyValue("IntermediateOutputPath"), Path.ChangeExtension(Path.GetFileName(target), ".xml"));
            return Path.GetFullPath(documentation, directory) == Path.GetFullPath(expected, directory);
        }

        Dictionary<string, string> DependencyCopies(ProjectGraphNode node)
        {
            var copies = new Dictionary<string, string>(StringComparer.Ordinal);
            var project = node.ProjectInstance;
            var directory = Path.GetDirectoryName(project.FullPath)!;
            var output = Path.GetDirectoryName(Path.GetFullPath(project.GetPropertyValue("TargetPath"), directory))!;
            var publish = project.GetPropertyValue("PublishDir");
            var destinations = publish.Length == 0 ? new[] { output } : new[] { output, Path.GetFullPath(publish, directory) };
            foreach (var dependency in Dependencies(node).OrderBy(current => Key(current.ProjectInstance), StringComparer.Ordinal))
            {
                var source = Path.GetFullPath(dependency.ProjectInstance.GetPropertyValue("TargetPath"), Path.GetDirectoryName(dependency.ProjectInstance.FullPath)!);
                foreach (var extension in new[] { ".dll", ".pdb", ".xml" })
                {
                    var producer = Relative(Path.ChangeExtension(source, extension));
                    foreach (var destination in destinations)
                    {
                        var target = Relative(Path.Combine(destination, Path.GetFileName(producer)));
                        if (copies.TryGetValue(target, out var existing) && existing != producer)
                        {
                            throw new InvalidDataException("Ambiguous graph dependency copy: " + target);
                        }
                        copies[target] = producer;
                    }
                }
            }
            return copies;
        }

        bool IsSdk(string path) => Path.GetFullPath(path).StartsWith(sdkRoot + Path.DirectorySeparatorChar, StringComparison.Ordinal);
        string Relative(string path)
        {
            var relative = WorkspaceView.Safe(Path.GetRelativePath(root, path).Replace('\\', '/'));
            var parent = Path.GetDirectoryName(Path.GetFullPath(path));
            while (parent is not null && parent != root)
            {
                if (File.Exists(Path.Combine(parent, "BUILD")) || File.Exists(Path.Combine(parent, "BUILD.bazel")))
                {
                    throw new InvalidDataException("Graph sync requires a root Bazel package: " + relative);
                }
                parent = Path.GetDirectoryName(parent);
            }
            return relative;
        }
        void Verify(string name, string expected, string header)
        {
            var path = Path.Combine(outputRoot, name);
            if (check && (!File.Exists(path) || File.ReadAllText(path) != expected))
            {
                throw new InvalidDataException(name + " is stale; run your graph-mode sync target (bazel run //:sync), then commit the generated files");
            }
            if (!check && File.Exists(path) && !File.ReadAllText(path).StartsWith(header, StringComparison.Ordinal))
            {
                throw new InvalidDataException("Refusing to overwrite an authored " + name);
            }
        }
    }

    private static string Key(Microsoft.Build.Execution.ProjectInstance project) => project.FullPath + "|" +
        string.Join(";", project.GlobalProperties.OrderBy(property => property.Key, StringComparer.Ordinal).Select(property => property.Key + "=" + property.Value));
}
