using System.Text.Json;
using Microsoft.Build.Definition;
using Microsoft.Build.Evaluation;
using Microsoft.Build.Evaluation.Context;
using Microsoft.Build.Graph;

namespace RulesMSBuild.ProjectSync;

// Package build logic is evaluated only through an explicit offline-restore opt-in.
// Authored targets require reviewed document contracts and declared task inputs.
internal static class GraphGenerator
{
    private const string Header = "# Generated by ProjectSync --graph. Edit project inputs, then synchronize again.\n";
    private const string ContractName = "graph.generated.json";
    private const string BuildName = "graph.generated.bzl";
    private static readonly string[] FileItems = ["Compile", "EmbeddedResource", "Content", "None", "AdditionalFiles", "Analyzer", "EditorConfigFiles", "GlobalAnalyzerConfigFiles", "RazorGenerate"];

    private static bool ImplicitPackageIsLocked(Project project, string id, HashSet<string> identities)
    {
        var assets = project.GetPropertyValue("ProjectAssetsFile");
        if (!File.Exists(assets))
        {
            return false;
        }
        using var json = JsonDocument.Parse(File.ReadAllText(assets));
        return json.RootElement.GetProperty("libraries").EnumerateObject().Any(library =>
            library.Name.StartsWith(id + "/", StringComparison.OrdinalIgnoreCase) && identities.Contains(library.Name) &&
            library.Value.GetProperty("type").GetString() == "package");
    }

    internal static void ValidateToolProperty(string name, Dictionary<string, string> properties)
    {
        System.Xml.XmlConvert.VerifyNCName(name);
        if (name.StartsWith("MSBuild", StringComparison.OrdinalIgnoreCase) || name.StartsWith("Restore", StringComparison.OrdinalIgnoreCase) ||
            name.StartsWith("_Bazel", StringComparison.OrdinalIgnoreCase) || name.Equals("PathMap", StringComparison.OrdinalIgnoreCase) || name.Equals("UseSharedCompilation", StringComparison.OrdinalIgnoreCase) || name.Equals("NetCoreSdkRoot", StringComparison.OrdinalIgnoreCase) || name.Equals("DOTNET_HOST_PATH", StringComparison.OrdinalIgnoreCase) || properties.ContainsKey(name))
        {
            throw new InvalidDataException("Reserved or conflicting graph tool property: " + name);
        }
    }

    internal static void Run(string root, string sdk, string[] entries, bool check, string outputRoot, string configuration = "Release", string framework = "", WorkspaceView? view = null, bool packageBuild = false, string[]? packageInputs = null, GraphMappings? mappings = null)
    {
        mappings ??= new GraphMappings(null);
        root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(root));
        sdk = Path.TrimEndingDirectorySeparator(sdk);
        var sdkRoot = Path.GetDirectoryName(Path.GetDirectoryName(sdk))!;
        var properties = new Dictionary<string, string>(mappings.Properties, StringComparer.OrdinalIgnoreCase) { ["Configuration"] = configuration };
        if (framework.Length != 0)
        {
            properties["TargetFramework"] = framework;
        }
        using var restored = packageBuild ? new GraphEvaluationWorkspace(root, sdkRoot, sdk, entries, properties,
            view ?? throw new InvalidDataException("Package build sync requires declared package inputs"), view?.GraphToolProperties) : null;
        if (restored is not null)
        {
            root = restored.Root;
        }
        using var collection = new ProjectCollection();
        var inputs = new System.Collections.Concurrent.ConcurrentDictionary<string, string[]>();
        var deferred = new System.Collections.Concurrent.ConcurrentDictionary<string, List<string>>();
        var outputs = new System.Collections.Concurrent.ConcurrentDictionary<string, string[]>();
        var definitions = new System.Collections.Concurrent.ConcurrentDictionary<string, byte>();
        var packageIdentities = view?.GraphPackageIdentities(packageBuild) ?? [];
        var evaluationProperties = new Dictionary<string, string>(properties)
        {
            ["ImportProjectExtensionProps"] = packageBuild ? "true" : "false",
            ["ImportProjectExtensionTargets"] = packageBuild ? "true" : "false",
            ["UseSharedCompilation"] = "false",
            ["NetCoreSdkRoot"] = sdk,
            ["PathMap"] = root + "=/_/workspace," + sdkRoot + "=/_/sdk"
        };
        foreach (var (name, path) in view?.GraphToolProperties ?? [])
        {
            ValidateToolProperty(name, evaluationProperties);
            evaluationProperties.Add(name, Path.Combine(root, path));
        }
        var entry = WorkspaceView.Safe(entries[0]);
        var evaluationContext = EvaluationContext.Create(EvaluationContext.SharingPolicy.Shared);
        var graph = new ProjectGraph(entries.Select(path => new ProjectGraphEntryPoint(Path.Combine(root, WorkspaceView.Safe(path)), evaluationProperties)), collection,
            (path, globals, projects) =>
            {
                var project = Project.FromFile(path, new ProjectOptions
                {
                    GlobalProperties = globals,
                    ProjectCollection = projects,
                    // Graph builds do not need IDE-only items from inactive conditions.
                    LoadSettings = ProjectLoadSettings.DoNotEvaluateElementsWithFalseCondition,
                    EvaluationContext = evaluationContext
                });
                if (project.Xml.Sdk is not ("Microsoft.NET.Sdk" or "Microsoft.NET.Sdk.Web" or "Microsoft.NET.Sdk.Razor") ||
                    project.GetItems("Reference").Any(reference =>
                    {
                        var value = reference.GetMetadataValue("HintPath");
                        var path = Path.GetFullPath((value.Length == 0 ? reference.EvaluatedInclude : value).Replace('\\', '/'), Path.GetDirectoryName(project.FullPath)!);
                        if (IsSdk(path) || IsRestored(path))
                        {
                            return false;
                        }
                        if (value.Length == 0 && project.GetPropertyValue("TargetFrameworkIdentifier") == ".NETFramework" &&
                            reference.EvaluatedInclude.IndexOfAny(['/', '\\', ',']) < 0)
                        {
                            var frameworkRoot = project.GetPropertyValue("TargetFrameworkRootPath");
                            if (Path.IsPathRooted(frameworkRoot) && IsRestored(frameworkRoot))
                            {
                                var framework = Path.Combine(frameworkRoot, ".NETFramework", project.GetPropertyValue("TargetFrameworkVersion"));
                                var profile = project.GetPropertyValue("TargetFrameworkProfile");
                                if (profile.Length != 0)
                                {
                                    framework = Path.Combine(framework, "Profile", profile);
                                }
                                return !File.Exists(Path.Combine(framework, reference.EvaluatedInclude + ".dll")) &&
                                    !File.Exists(Path.Combine(framework, "Facades", reference.EvaluatedInclude + ".dll"));
                            }
                        }
                        return true;
                    }))
                {
                    throw new InvalidDataException("Graph sync requires a supported .NET SDK project with SDK/package-owned assembly references: " + Relative(path) + "; " +
                        string.Join("; ", project.GetItems("Reference").Select(item => item.EvaluatedInclude + "=" + item.GetMetadataValue("HintPath"))));
                }
                foreach (var package in project.GetItems("PackageReference"))
                {
                    var version = package.GetMetadataValue("VersionOverride");
                    if (version.Length == 0)
                    {
                        version = package.GetMetadataValue("Version");
                    }
                    if (version.Length == 0 && project.GetPropertyValue("ManagePackageVersionsCentrally").Equals("true", StringComparison.OrdinalIgnoreCase))
                    {
                        version = project.GetItems("PackageVersion").SingleOrDefault(item => item.EvaluatedInclude.Equals(package.EvaluatedInclude, StringComparison.OrdinalIgnoreCase))?.GetMetadataValue("Version") ?? "";
                    }
                    var identity = package.EvaluatedInclude + "/" + version;
                    if (!packageIdentities.Contains(identity) && !(packageBuild && package.GetMetadataValue("IsImplicitlyDefined").Equals("true", StringComparison.OrdinalIgnoreCase) &&
                        ImplicitPackageIsLocked(project, package.EvaluatedInclude, packageIdentities)))
                    {
                        throw new InvalidDataException(Relative(path) + ": PackageReference " + identity + " requires an exact entry in msbuild_sync.package_lock; declare the closed package set and rerun sync");
                    }
                }
                var documents = project.Imports.Select(import => import.ImportedProject).Append(project.Xml)
                    .Where(document => !IsSdk(document.FullPath) && !IsRestored(document.FullPath)).DistinctBy(document => document.FullPath).ToArray();
                var binding = mappings.ForProject(Relative(path), project.GetPropertyValue("TargetFramework"));
                var taskInputs = documents.SelectMany(document => GraphMappings.Inputs(document, Relative(document.FullPath), binding)).ToArray();
                var unsupportedItems = project.AllEvaluatedItems
                    .Where(item => !IsSdk(item.Xml.ContainingProject.FullPath) && !IsRestored(item.Xml.ContainingProject.FullPath))
                    .Select(item => item.ItemType).Distinct(StringComparer.Ordinal)
                    .Where(type => !FileItems.Contains(type, StringComparer.Ordinal) && !binding.InputItems.ContainsKey(type) &&
                        !binding.EvaluationItems.Contains(type, StringComparer.Ordinal) && type is not "PackageReference" and not "PackageVersion" and not "GlobalPackageReference" and not "ProjectReference" and not "InternalsVisibleTo" and not "Using" and not "FrameworkReference" and not "Reference" and not "AssemblyAttribute")
                    .Order(StringComparer.Ordinal).ToArray();
                if (unsupportedItems.Length != 0)
                {
                    throw new InvalidDataException("Graph sync item requires contract transfer in " + Relative(path) + ": " + string.Join(", ", unsupportedItems));
                }
                var declared = new HashSet<string>(documents.Select(document => Relative(document.FullPath)), StringComparer.Ordinal);
                foreach (var document in declared)
                {
                    definitions.TryAdd(document, 0);
                }
                foreach (var input in taskInputs)
                {
                    if (!File.Exists(Path.Combine(root, input)))
                    {
                        throw new InvalidDataException("Missing declared graph task input: " + input);
                    }
                    declared.Add(input);
                }
                var signingKey = project.GetPropertyValue("AssemblyOriginatorKeyFile");
                if (signingKey.Length != 0)
                {
                    var keyPath = Path.GetFullPath(signingKey.Replace('\\', '/'), Path.GetDirectoryName(project.FullPath)!);
                    if (!File.Exists(keyPath))
                    {
                        throw new InvalidDataException("Missing signing key input: " + keyPath);
                    }
                    if (!IsSdk(keyPath) && !IsRestored(keyPath))
                    {
                        declared.Add(Relative(keyPath));
                    }
                }
                var generated = new List<string>();
                foreach (var item in FileItems.Concat(binding.InputItems.Keys).SelectMany(project.GetItems))
                {
                    var fullPath = item.GetMetadataValue("FullPath");
                    if (fullPath.Length == 0 || IsSdk(fullPath) || IsRestored(fullPath))
                    {
                        continue;
                    }
                    if (!File.Exists(fullPath) && (IsSdk(item.Xml.ContainingProject.FullPath) ||
                        (item.ItemType == "GlobalAnalyzerConfigFiles" && IsRestored(item.Xml.ContainingProject.FullPath))))
                    {
                        continue;
                    }
                    if (Path.GetRelativePath(root, fullPath).StartsWith("../", StringComparison.Ordinal))
                    {
                        throw new InvalidDataException("Graph item outside workspace: " + item.ItemType + " " + fullPath + " from " + item.Xml.ContainingProject.FullPath);
                    }
                    var relative = Relative(fullPath);
                    if (relative is ContractName or BuildName)
                    {
                        continue;
                    }
                    generated.Add(relative);
                }
                var instance = project.CreateProjectInstance();
                outputs[Key(instance)] = instance.GetPropertyValue("TargetPath").Length == 0 ? [] : binding.OutputFiles
                    .SelectMany(value => project.ExpandString(value).Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                    .Select(value => Relative(Path.GetFullPath(value.Replace('\\', '/'), root)))
                    .Distinct().Order(StringComparer.Ordinal).ToArray();
                deferred[Key(instance)] = generated;
                inputs[Key(instance)] = declared.Order(StringComparer.Ordinal).ToArray();
                return instance;
            });
        var dependencyClosure = new Dictionary<ProjectGraphNode, HashSet<ProjectGraphNode>>();
        foreach (var node in graph.ProjectNodes)
        {
            var files = inputs[Key(node.ProjectInstance)].ToHashSet(StringComparer.Ordinal);
            var produced = Dependencies(node).Append(node).SelectMany(dependency =>
                outputs[Key(dependency.ProjectInstance)].Select(path => Path.Combine(root, path))
                    .Append(dependency.ProjectInstance.GetPropertyValue("TargetPath"))).ToHashSet(StringComparer.Ordinal);
            foreach (var path in deferred[Key(node.ProjectInstance)])
            {
                // ProjectReference outputs are scheduled by MSBuild. They are
                // dependency results, never source files copied from a prior build.
                if (produced.Contains(Path.Combine(root, path)))
                {
                    continue;
                }
                if (!File.Exists(Path.Combine(root, path)))
                {
                    throw new InvalidDataException("Graph sync input does not exist and has no project producer: " + path);
                }
                files.Add(path);
            }
            inputs[Key(node.ProjectInstance)] = files.Order(StringComparer.Ordinal).ToArray();
        }
        var boundaries = new Dictionary<ProjectGraphNode, bool>();
        var declarations = new SortedDictionary<string, object>(StringComparer.Ordinal);
        foreach (var group in graph.ProjectNodes.GroupBy(node => Relative(node.ProjectInstance.FullPath)))
        {
            // Including the union makes an absent global property explicit. This
            // prevents an outer-node selector from also matching an inner node.
            var selectorKeys = group.SelectMany(node => node.ProjectInstance.GlobalProperties.Keys)
                .Where(key => !evaluationProperties.ContainsKey(key) || properties.ContainsKey(key))
                .Distinct(StringComparer.OrdinalIgnoreCase).Order(StringComparer.Ordinal).ToArray();
            var configurations = group.OrderBy(node => Key(node.ProjectInstance), StringComparer.Ordinal).Select(node => new
            {
                Properties = selectorKeys.ToDictionary(key => key, key => node.ProjectInstance.GlobalProperties.TryGetValue(key, out var value) ? value : ""),
                Inputs = inputs[Key(node.ProjectInstance)],
                OutputFiles = outputs[Key(node.ProjectInstance)],
                ReferenceBoundary = CanUseReferenceBoundary(node),
                ImplementationDependencies = ImplementationDependencies(node),
                DependencyCopies = CanUseReferenceBoundary(node) ? DependencyCopies(node) : new Dictionary<string, string>(),
                OutputDirectories = node.ProjectInstance.GetPropertyValue("TargetPath").Length == 0 ? [] :
                    new[] { "OutputPath", "IntermediateOutputPath" }.Select(property =>
                    {
                        var value = node.ProjectInstance.GetPropertyValue(property);
                        if (value.Length == 0)
                        {
                            throw new InvalidDataException("Missing graph output property: " + property);
                        }
                        return Relative(Path.TrimEndingDirectorySeparator(Path.GetFullPath(value.Replace('\\', '/'), Path.GetDirectoryName(node.ProjectInstance.FullPath)!)));
                    }).Distinct().ToArray()
            }).ToArray();
            declarations.Add(group.Key, new
            {
                Inputs = Array.Empty<string>(),
                OutputDirectories = Array.Empty<string>(),
                Configurations = configurations
            });
        }
        var shared = (File.Exists(Path.Combine(root, "global.json")) ? new[] { "global.json" } : []).Concat(packageInputs ?? []).Distinct().Order(StringComparer.Ordinal).ToArray();
        foreach (var path in shared)
        {
            if (!File.Exists(Path.Combine(root, WorkspaceView.Safe(path))))
            {
                throw new InvalidDataException("Missing declared package task input: " + path);
            }
        }
        var restore = GraphRestoreGenerator.Create(graph, mappings, definitions.Keys, shared, Relative);
        if (restore is not null)
        {
            shared = shared.Concat(restore.Inputs.Except(definitions.Keys)).Distinct().Order(StringComparer.Ordinal).ToArray();
            foreach (var path in restore.Inputs)
            {
                if (!File.Exists(Path.Combine(root, path)))
                {
                    throw new InvalidDataException("Missing declared Restore input: " + path);
                }
            }
        }
        var inputDirectories = graph.ProjectNodes.SelectMany(node => mappings.ForProject(Relative(node.ProjectInstance.FullPath),
            node.ProjectInstance.GetPropertyValue("TargetFramework")).InputDirectories).Select(WorkspaceView.Safe).Distinct().Order(StringComparer.Ordinal).ToArray();
        foreach (var directory in inputDirectories)
        {
            if (!Directory.Exists(Path.Combine(root, directory)))
            {
                throw new InvalidDataException("Declared input directory must exist during sync: " + directory);
            }
        }
        var contractData = JsonSerializer.SerializeToNode(new
        {
            GeneratedBy = "ProjectSync --graph",
            Version = graph.ProjectNodes.Select(node => mappings.ForProject(Relative(node.ProjectInstance.FullPath), node.ProjectInstance.GetPropertyValue("TargetFramework")))
                .Any(binding => binding.ReferenceBoundary == true || binding.ImplementationDependencies.Length != 0) ? 3 : 2,
            Entry = entry,
            Entries = entries,
            SdkVersion = Path.GetFileName(sdk),
            Properties = properties,
            ToolProperties = view?.GraphToolProperties ?? [],
            SharedInputs = shared,
            PackageDigests = view?.GraphPackageDigests() ?? [],
            DefinitionDigests = definitions.Keys.Order(StringComparer.Ordinal).ToDictionary(path => path,
                path => Convert.ToHexStringLower(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(Path.Combine(root, path))))),
            Projects = declarations
        })!;
        if (restore is not null)
        {
            contractData["Restore"] = JsonSerializer.SerializeToNode(restore);
        }
        if (inputDirectories.Length != 0)
        {
            contractData["Version"] = 4;
            contractData["InputDirectories"] = JsonSerializer.SerializeToNode(inputDirectories);
        }
        var contract = contractData.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n";
        var sources = inputs.Values.SelectMany(files => files).Concat(shared).Concat(restore?.Inputs ?? []).Distinct().Order(StringComparer.Ordinal).ToArray();
        var runtimeOutputs = graph.ProjectNodes.Where(node => node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 &&
            node.ProjectInstance.GetPropertyValue("TargetFramework").Length != 0).OrderBy(node => Key(node.ProjectInstance), StringComparer.Ordinal).ToDictionary(
            node => Relative(node.ProjectInstance.FullPath) + "|" + node.ProjectInstance.GetPropertyValue("TargetFramework"),
            node => new[] { Relative(Path.GetDirectoryName(node.ProjectInstance.GetPropertyValue("TargetPath"))!),
                Path.GetFileName(node.ProjectInstance.GetPropertyValue("TargetPath")), node.ProjectInstance.GetPropertyValue("OutputType") });
        var publishOutputs = graph.ProjectNodes.Where(node => node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 &&
            node.ProjectInstance.GetPropertyValue("TargetFramework").Length != 0 && node.ProjectInstance.GetPropertyValue("PublishDir").Length != 0)
            .OrderBy(node => Key(node.ProjectInstance), StringComparer.Ordinal).ToDictionary(
                node => Relative(node.ProjectInstance.FullPath) + "|" + node.ProjectInstance.GetPropertyValue("TargetFramework"),
                node => new[] { Relative(Path.TrimEndingDirectorySeparator(Path.GetFullPath(node.ProjectInstance.GetPropertyValue("PublishDir"), Path.GetDirectoryName(node.ProjectInstance.FullPath)!))),
                    Path.GetFileName(node.ProjectInstance.GetPropertyValue("TargetPath")), node.ProjectInstance.GetPropertyValue("OutputType") });
        var restoreRule = restore is null ? "" :
            "    if not linux_stable_paths:\n        fail(\"Prepared Restore requires linux_stable_paths\")\n" +
            "    msbuild_graph_restore(\n        name = name + \"_restore\",\n        runner = \":\" + name + \"_runner\",\n        contract = \"" + ContractName + "\",\n        linux_stable_paths = True,\n" +
            "        srcs = " + StarlarkLiteral.Serialize(restore.Inputs.Where(path => view?.Labels.ContainsKey(path) != true && !path.StartsWith(".graph-tools/", StringComparison.Ordinal)).ToArray()) + ",\n" +
            "        bindings = " + StarlarkLiteral.Serialize(view?.GraphBindingLabels ?? []) + ",\n" +
            "        input_paths = " + StarlarkLiteral.Serialize(view?.Bindings(restore.Inputs) ?? []) + ",\n" +
            (view?.DefaultPackageLock is null ? "" : "        package_lock = " + StarlarkLiteral.Serialize(view.DefaultPackageLock) + ",\n") + "    )\n";
        var text = Header + "load(\"@rules_msbuild//msbuild:defs.bzl\", \"msbuild_graph\", \"msbuild_graph_runner\"" + (restore is null ? "" : ", \"msbuild_graph_restore\"") + ")\n\n" +
            "def app_graph(name = \"app\", linux_stable_paths = False, target = \"Build\", linux_worker = False, worker_cache_mb = 4096):\n    if native.package_name():\n        fail(\"app_graph must be called from the workspace root\")\n" +
            "    msbuild_graph_runner(name = name + \"_runner\")\n" + restoreRule + "    msbuild_graph(\n        name = name,\n        linux_stable_paths = linux_stable_paths,\n        linux_worker = linux_worker,\n        worker_cache_mb = worker_cache_mb,\n        target = target,\n        runner = \":\" + name + \"_runner\",\n" +
            (restore is null ? "" : "        restore = \":\" + name + \"_restore\",\n") +
            "        contract = \"" + ContractName + "\",\n        srcs = " + StarlarkLiteral.Serialize(sources.Where(path => view?.Labels.ContainsKey(path) != true && !path.StartsWith(".graph-tools/", StringComparison.Ordinal)).ToArray()) + ",\n        bindings = " + StarlarkLiteral.Serialize(view?.GraphBindingLabels ?? []) + ",\n        input_paths = " + StarlarkLiteral.Serialize(view?.Bindings(sources) ?? []) + ",\n        project_outputs = " + StarlarkLiteral.Serialize(runtimeOutputs) + ",\n        publish_outputs = " + StarlarkLiteral.Serialize(publishOutputs) + ",\n" + (view?.DefaultPackageLock is null ? "" : "        package_lock = " + StarlarkLiteral.Serialize(view.DefaultPackageLock) + ",\n") + "    )\n";
        // Validate both destinations before replacing either generated file.
        Verify(ContractName, contract, "{\n  \"GeneratedBy\": \"ProjectSync --graph\",");
        Verify(BuildName, text, Header);
        if (!check)
        {
            File.WriteAllText(Path.Combine(outputRoot, ContractName), contract);
            File.WriteAllText(Path.Combine(outputRoot, BuildName), text);
        }

        IEnumerable<ProjectGraphNode> Dependencies(ProjectGraphNode node)
        {
            if (dependencyClosure.TryGetValue(node, out var existing))
            {
                return existing;
            }
            var seen = new HashSet<ProjectGraphNode>();
            var pending = new Stack<ProjectGraphNode>(node.ProjectReferences);
            while (pending.TryPop(out var dependency))
            {
                if (seen.Add(dependency))
                {
                    foreach (var child in dependency.ProjectReferences)
                    {
                        pending.Push(child);
                    }
                }
            }
            dependencyClosure.Add(node, seen);
            return seen;
        }
        string[] ImplementationDependencies(ProjectGraphNode node)
        {
            var binding = mappings.ForProject(Relative(node.ProjectInstance.FullPath), node.ProjectInstance.GetPropertyValue("TargetFramework"));
            foreach (var path in binding.ImplementationDependencies)
            {
                WorkspaceView.Safe(path);
                if (!node.ProjectReferences.Any(dependency => Relative(dependency.ProjectInstance.FullPath) == path))
                {
                    throw new InvalidDataException("Implementation dependency must be a direct ProjectReference: " + path);
                }
            }
            return binding.ImplementationDependencies.Distinct().Order(StringComparer.Ordinal).ToArray();
        }
        bool CanUseReferenceBoundary(ProjectGraphNode node)
        {
            if (boundaries.TryGetValue(node, out var boundary))
            {
                return boundary;
            }
            var binding = mappings.ForProject(Relative(node.ProjectInstance.FullPath), node.ProjectInstance.GetPropertyValue("TargetFramework"));
            if (binding.ReferenceBoundary is not null)
            {
                var supported = node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 &&
                    Dependencies(node).Append(node).All(current =>
                        (current.ProjectInstance.GetPropertyValue("TargetPath").Length == 0 || HasStandardSymbols(current)) &&
                        new[] { "PublishTrimmed", "PublishReadyToRun", "PublishAot", "PublishSingleFile" }.All(property =>
                            !current.ProjectInstance.GetPropertyValue(property).Equals("true", StringComparison.OrdinalIgnoreCase)));
                if (binding.ReferenceBoundary == true && node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 && !supported)
                {
                    throw new InvalidDataException("Reviewed reference boundary requires standard managed outputs without publish transforms: " + Relative(node.ProjectInstance.FullPath));
                }
                return boundaries[node] = binding.ReferenceBoundary == true && supported;
            }
            return boundaries[node] = node.ProjectInstance.GetPropertyValue("TargetPath").Length != 0 &&
            Dependencies(node).Append(node).All(current =>
                !current.ProjectInstance.GetPropertyValue("UsingMicrosoftNETSdkRazor").Equals("true", StringComparison.OrdinalIgnoreCase) &&
                mappings.ForProject(Relative(current.ProjectInstance.FullPath), current.ProjectInstance.GetPropertyValue("TargetFramework")).Documents.Count == 0 &&
                mappings.ForProject(Relative(current.ProjectInstance.FullPath), current.ProjectInstance.GetPropertyValue("TargetFramework")).InputItems.Count == 0 &&
                mappings.ForProject(Relative(current.ProjectInstance.FullPath), current.ProjectInstance.GetPropertyValue("TargetFramework")).OutputFiles.Length == 0 &&
                new[] { "PublishTrimmed", "PublishReadyToRun", "PublishAot", "PublishSingleFile" }.All(property =>
                    !current.ProjectInstance.GetPropertyValue(property).Equals("true", StringComparison.OrdinalIgnoreCase)) &&
                current.ProjectInstance.GetItems("ProjectReference").All(item =>
                    item.GetMetadataValue("OutputItemType").Length == 0 &&
                    item.GetMetadataValue("Targets").Length == 0 &&
                    item.GetMetadataValue("ReferenceOutputAssembly") is "" or "true" &&
                    item.GetMetadataValue("Private") is "" or "true") &&
                (current == node || current.ProjectInstance.GetPropertyValue("OutputType").Equals("Library", StringComparison.OrdinalIgnoreCase)) &&
                current.ProjectInstance.GetItems("PackageReference").Count == 0 &&
                HasStandardSymbols(current) &&
                current.ProjectInstance.GetItems("EmbeddedResource").Count == 0 &&
                FileItems.SelectMany(current.ProjectInstance.GetItems).All(item =>
                    item.GetMetadataValue("CopyToOutputDirectory") is "" or "Never" &&
                    item.GetMetadataValue("CopyToPublishDirectory") is "" or "Never"));
        }

        bool HasStandardSymbols(ProjectGraphNode node)
        {
            var project = node.ProjectInstance;
            var target = project.GetPropertyValue("TargetPath");
            if (Path.GetExtension(target) != ".dll" || project.GetPropertyValue("PdbFile").Length != 0)
            {
                return false;
            }
            var documentation = project.GetPropertyValue("DocumentationFile");
            if (documentation.Length == 0)
            {
                return true;
            }
            var directory = Path.GetDirectoryName(project.FullPath)!;
            var expected = Path.Combine(project.GetPropertyValue("IntermediateOutputPath"), Path.ChangeExtension(Path.GetFileName(target), ".xml"));
            return Path.GetFullPath(documentation, directory) == Path.GetFullPath(expected, directory);
        }

        Dictionary<string, string> DependencyCopies(ProjectGraphNode node)
        {
            var copies = new Dictionary<string, string>(StringComparer.Ordinal);
            var project = node.ProjectInstance;
            var directory = Path.GetDirectoryName(project.FullPath)!;
            var output = Path.GetDirectoryName(Path.GetFullPath(project.GetPropertyValue("TargetPath"), directory))!;
            var publish = project.GetPropertyValue("PublishDir");
            var destinations = publish.Length == 0 ? new[] { output } : new[] { output, Path.GetFullPath(publish, directory) };
            foreach (var dependency in Dependencies(node).Where(current => current.ProjectInstance.GetPropertyValue("TargetPath").Length != 0)
                .OrderBy(current => Key(current.ProjectInstance), StringComparer.Ordinal))
            {
                var source = Path.GetFullPath(dependency.ProjectInstance.GetPropertyValue("TargetPath"), Path.GetDirectoryName(dependency.ProjectInstance.FullPath)!);
                foreach (var extension in new[] { ".dll", ".pdb", ".xml" })
                {
                    var producer = Relative(Path.ChangeExtension(source, extension));
                    foreach (var destination in destinations)
                    {
                        var target = Relative(Path.Combine(destination, Path.GetFileName(producer)));
                        if (copies.TryGetValue(target, out var existing) && existing != producer)
                        {
                            throw new InvalidDataException("Ambiguous graph dependency copy: " + target);
                        }
                        copies[target] = producer;
                    }
                }
            }
            return copies;
        }

        bool IsRestored(string path)
        {
            var relative = Path.GetRelativePath(root, path).Replace('\\', '/');
            return packageBuild && (relative.StartsWith(".nuget/", StringComparison.Ordinal) ||
                relative.EndsWith(".nuget.g.props", StringComparison.Ordinal) || relative.EndsWith(".nuget.g.targets", StringComparison.Ordinal));
        }
        bool IsSdk(string path) => Path.GetFullPath(path).StartsWith(sdkRoot + Path.DirectorySeparatorChar, StringComparison.Ordinal);
        string Relative(string path)
        {
            var relative = WorkspaceView.Safe(Path.GetRelativePath(root, path).Replace('\\', '/'));
            var parent = Path.GetDirectoryName(Path.GetFullPath(path));
            while (parent is not null && parent != root)
            {
                if (File.Exists(Path.Combine(parent, "BUILD")) || File.Exists(Path.Combine(parent, "BUILD.bazel")))
                {
                    throw new InvalidDataException("Graph sync requires a root Bazel package: " + relative);
                }
                parent = Path.GetDirectoryName(parent);
            }
            return relative;
        }
        void Verify(string name, string expected, string header)
        {
            var path = Path.Combine(outputRoot, name);
            if (check && (!File.Exists(path) || File.ReadAllText(path) != expected))
            {
                throw new InvalidDataException(name + " is stale; run your graph-mode sync target (bazel run //:sync), then commit the generated files");
            }
            if (!check && File.Exists(path) && !File.ReadAllText(path).StartsWith(header, StringComparison.Ordinal))
            {
                throw new InvalidDataException("Refusing to overwrite an authored " + name);
            }
        }
    }

    private static string Key(Microsoft.Build.Execution.ProjectInstance project) => project.FullPath + "|" +
        string.Join(";", project.GlobalProperties.OrderBy(property => property.Key, StringComparer.Ordinal).Select(property => property.Key + "=" + property.Value));
}
