<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../MSBuildTool.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Build" HintPath="$(RulesMSBuildEngineRoot)/Microsoft.Build.dll" Private="true" />
    <Reference Include="Microsoft.Build.Framework" HintPath="$(RulesMSBuildEngineRoot)/Microsoft.Build.Framework.dll" Private="true" />
    <Reference Include="Microsoft.Build.Utilities.Core" HintPath="$(RulesMSBuildEngineRoot)/Microsoft.Build.Utilities.Core.dll" Private="true" />
  </ItemGroup>
</Project>
