exports_files(
    glob(
        ["*.bzl"],
        exclude = ["sdk_bootstrap.bzl"],
    ),
    visibility = ["//msbuild:__pkg__"],
)

exports_files(
    ["sdk_bootstrap.bzl"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "integration_sources",
    srcs = glob(["*.bzl"]) + ["BUILD.bazel"],
    visibility = ["//msbuild:__pkg__"],
)
