namespace RulesMSBuild.Tooling;

internal static class Program
{
    public static int Main(string[] args)
    {
        try
        {
            Run(args);
            return 0;
        }
        catch (Exception error) { Console.Error.WriteLine(error.Message); return 1; }
    }
    private static void Run(string[] args)
    {
        if (args.Length < 2)
        {
            throw new ArgumentException("tooling <repository> <check|setup-starlark>");
        }

        var root = Host.Real(args[0]);
        var command = args[1];
        var pins = Json.Read(Path.Combine(root, "scripts/toolchains.json"));
        var version = Json.Read(Path.Combine(root, "global.json"))["sdk"]!.String("version");
        if (pins["dotnet"]!.String("version") != version)
        {
            throw new InvalidDataException("Toolchain pins differ");
        }

        var shellPins = File.ReadAllText(Path.Combine(root, "scripts/toolchain-pins.sh"));
        foreach (var name in new[] { "dotnet", "bazelisk" })
        {
            foreach (var arch in new[] { "linux-x64", "linux-arm64", "osx-arm64" })
            {
                var pin = pins[name]!;
                var platform = pin["platforms"]?[arch];
                foreach (var field in new[] { "version", "url", "sha256" })
                {
                    var value = (platform?[field] ?? pin[field])!.GetValue<string>();
                    if (!shellPins.Contains(name + "_" + field + "=" + value + "\n", StringComparison.Ordinal))
                    {
                        throw new InvalidDataException("Bootstrap pin differs from JSON: " + name + " " + field);
                    }
                }
                Digest((platform?["sha256"] ?? pin["sha256"])!.GetValue<string>());
                if (!(platform?["url"] ?? pin["url"])!.GetValue<string>().StartsWith("https://", StringComparison.Ordinal))
                {
                    throw new InvalidDataException("HTTPS download required");
                }
            }
        }

        if (command == "setup-starlark")
        {
            StarlarkTools.Setup(root);
            return;
        }
        if (command != "check")
        {
            throw new ArgumentException("Unknown tooling command");
        }

        var sdk = Environment.GetEnvironmentVariable("DOTNET_ROOT") ?? Path.Combine(root, ".tools/dotnet");
        if (Host.Run(Path.Combine(sdk, "dotnet"), ["--version"], root).Trim() != version)
        {
            throw new InvalidDataException("SDK version differs");
        }

        var bazel = Environment.GetEnvironmentVariable("RULES_MSBUILD_BAZEL") ?? Path.Combine(root, "scripts/bazel-launcher.sh");
        var actual = Host.Run(bazel, ["--version"], root).Trim();
        var expected = "bazel " + (Environment.GetEnvironmentVariable("USE_BAZEL_VERSION") ?? Environment.GetEnvironmentVariable("RULES_MSBUILD_BAZEL_VERSION") ?? File.ReadAllText(Path.Combine(root, ".bazelversion")).Trim());
        if (actual != expected && actual != expected + "- (@non-git)")
        {
            throw new InvalidDataException("Bazel version differs: " + actual);
        }

        if (args.Skip(2).Contains("--toolchain-only"))
        {
            Console.WriteLine("Toolchain checks passed");
            return;
        }
        var binary = StarlarkTools.Buildifier(root);

        IEnumerable<string> files;
        bool IsStarlark(string path) => path.EndsWith(".bzl", StringComparison.Ordinal) || Path.GetFileName(path) is "BUILD" or "BUILD.bazel" or "MODULE.bazel";
        if (Path.Exists(Path.Combine(root, ".git")))
        {
            files = Host.Run("git", ["ls-files", "-z", "--cached", "--others", "--exclude-standard"], root).Split('\0', StringSplitOptions.RemoveEmptyEntries).Where(IsStarlark).Select(p => Path.Combine(root, p));
        }
        else
        {
            files = Enumerate(root).Where(IsStarlark);
        }

        var selected = files.Distinct().Order(StringComparer.Ordinal).ToArray();
        if (selected.Length == 0)
        {
            throw new InvalidDataException("No Starlark files found");
        }

        // ProjectSync owns generated formatting. Parse these files, but verify their
        // exact contents with the example's sync --check rather than reformatting.
        var generated = selected.Where(path => Path.GetFileName(path) == "projects.generated.bzl" && File.ReadLines(path).FirstOrDefault() == "# Generated by ProjectSync. Edit project inputs, then synchronize again.").ToArray();
        var authored = selected.Except(generated).ToArray();
        if (authored.Length > 0)
        {
            Host.Run(binary, new[] { "-mode=check", "-lint=warn" }.Concat(authored), root);
        }
        if (generated.Length > 0)
        {
            Host.Run(binary, new[] { "-mode=print_if_changed", "-lint=off" }.Concat(generated), root);
        }
        Console.WriteLine("Toolchain and Starlark checks passed");
    }
    private static void Digest(string value)
    {
        if (value.Length != 64 || !value.All(char.IsAsciiHexDigitLower))
        {
            throw new InvalidDataException("Invalid tool digest");
        }
    }
    private static IEnumerable<string> Enumerate(string root)
    {
        foreach (var path in Directory.GetFileSystemEntries(root))
        {
            FileSystemInfo info = Directory.Exists(path) ? new DirectoryInfo(path) : new FileInfo(path);
            if (info.LinkTarget is not null)
            {
                continue;
            }

            if (!Directory.Exists(path))
            {
                yield return path;
                continue;
            }
            if (Path.GetFileName(path) is ".git" or ".tools" or ".cache" or "artifacts" or "bin" or "obj" or "__pycache__" || Path.GetFileName(path).StartsWith("bazel-", StringComparison.Ordinal))
            {
                continue;
            }

            foreach (var file in Enumerate(path))
            {
                yield return file;
            }
        }
    }
}
