<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Shared.$(Flavor)</AssemblyName>
    <DefineConstants Condition="'$(Flavor)' == 'red'">$(DefineConstants);RED</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" GlobalPropertiesToRemove="Flavor"/>
  </ItemGroup>
</Project>
