exports_files([
    "GraphBuild.csproj",
    "BUILD.bazel",
])

filegroup(
    name = "sources",
    srcs = glob(["*.cs"]) + [
        "GraphBuild.csproj",
        "//tools:Directory.Build.props",
        "//tools:GraphCompilerReferences.cs",
        "//tools:GraphEntryProperties.cs",
        "//tools:MSBuildTool.props",
        "//tools:PackageSdks.cs",
        "//tools/ProjectCache:RemoteSnapshotStore.cs",
    ],
    visibility = ["//visibility:public"],
)
