exports_files(["GraphBuild.csproj"])

filegroup(
    name = "sources",
    srcs = glob(["*.cs"]) + [
        "GraphBuild.csproj",
        "//tools:Directory.Build.props",
        "//tools:MSBuildTool.props",
        "//tools/ProjectCache:RemoteSnapshotStore.cs",
    ],
    visibility = ["//visibility:public"],
)
