load("@rules_msbuild//msbuild:defs.bzl", "msbuild_graph_binary", "msbuild_graph_test")
load("@rules_msbuild//msbuild:sync.bzl", "msbuild_sync")
load(":graph.generated.bzl", "app_graph")

exports_files(["global.json"])

msbuild_sync(
    name = "sync",
    projects = [
        "App/App.csproj",
        "Tests/Tests.csproj",
    ],
)

app_graph(name = "graph")

msbuild_graph_binary(
    name = "app",
    graph = ":graph",
    project = "App/App.csproj",
)

msbuild_graph_test(
    name = "tests",
    graph = ":graph",
    project = "Tests/Tests.csproj",
)
