# Generated by ProjectSync. Edit project inputs, then synchronize again.
load("@rules_msbuild//msbuild:defs.bzl", "msbuild_graph", "msbuild_graph_runner")

def app_graph(name = "app", linux_stable_paths = False, target = "Build", linux_worker = False, worker_cache_mb = 4096, profile_build = False):
    if native.package_name():
        fail("app_graph must be called from the workspace root")
    msbuild_graph_runner(name = name + "_runner")
    msbuild_graph(
        name = name,
        linux_stable_paths = linux_stable_paths,
        linux_worker = linux_worker,
        worker_cache_mb = worker_cache_mb,
        profile_build = profile_build,
        target = target,
        runner = ":" + name + "_runner",
        contract = "graph.generated.json",
        srcs = ["App/App.csproj","App/Program.cs","Library/Library.csproj","Library/Message.cs","Tests/Program.cs","Tests/Tests.csproj","global.json"],
        bindings = [],
        input_paths = {},
        project_outputs = {"App/App.csproj|net10.0":["App/bin/Release/net10.0","App.dll","Exe"],"Library/Library.csproj|net10.0":["Library/bin/Release/net10.0","Library.dll","Library"],"Tests/Tests.csproj|net10.0":["Tests/bin/Release/net10.0","Tests.dll","Exe"]},
        publish_outputs = {"App/App.csproj|net10.0":["App/bin/Release/net10.0/publish","App.dll","Exe"],"Library/Library.csproj|net10.0":["Library/bin/Release/net10.0/publish","Library.dll","Library"],"Tests/Tests.csproj|net10.0":["Tests/bin/Release/net10.0/publish","Tests.dll","Exe"]},
    )
