# Generated by ProjectSync. Edit project inputs, then synchronize again.
load("@rules_msbuild//msbuild:defs.bzl", "msbuild_binary", "msbuild_items", "msbuild_project", "msbuild_test_project")

def app_projects():
    if native.package_name():
        fail("app_projects must be called from the workspace root")
    msbuild_binary(
        name = "App_App",
        project = "App/App.csproj",
        configuration = "Release",
        msbuild_properties = {"Platform":"AnyCPU"},
        target_framework = "net10.0",
        srcs = ["App/Program.cs"],
        deps = [":Library_Library"],
        nullable = "disable",
        lang_version = "14.0",
    )

    msbuild_project(
        name = "Library_Library",
        project = "Library/Library.csproj",
        configuration = "Release",
        msbuild_properties = {"Platform":"AnyCPU"},
        target_frameworks = ["net10.0"],
        framework_overrides = {
            "net10.0": {
                "srcs": ["Library/Message.cs"],
                "nullable": "disable",
                "lang_version": "14.0",
                "use_apphost": False,
            },
        },
    )

    msbuild_test_project(
        name = "Tests_Tests",
        project = "Tests/Tests.csproj",
        configuration = "Release",
        msbuild_properties = {"Platform":"AnyCPU"},
        target_frameworks = ["net10.0"],
        framework_overrides = {
            "net10.0": {
                "srcs": ["Tests/Program.cs"],
                "deps": [":Library_Library"],
                "test_output_type": "exe",
                "nullable": "disable",
                "lang_version": "14.0",
            },
        },
    )
